package kz.eco.pek.docgen;

import kz.eco.common.exception.BadRequestException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;

/**
 * DOCX -> PDF conversion for PEK final reports, via the same LibreOffice-headless approach
 * kz.eco.protocol.ProtocolDocumentGenerationService uses, with the same fallback to a minimal
 * built-in PDF when LibreOffice is unavailable (local/CI environments) - duplicated here rather
 * than shared because ProtocolDocumentGenerationService's converter is a private method, not a
 * reusable component; extracting a shared utility was out of scope for this iteration.
 */
final class PekReportPdfConverter {

    private static final Logger log = LoggerFactory.getLogger(PekReportPdfConverter.class);

    private PekReportPdfConverter() {
    }

    static byte[] convert(byte[] docxBytes, PekReportDocValues values) {
        try {
            return convertViaLibreOffice(docxBytes);
        } catch (IOException conversionFailure) {
            log.warn("LibreOffice conversion unavailable for PEK report, using built-in PDF renderer: {}",
                    conversionFailure.getMessage());
            return values != null ? renderFallbackPdf(values) : renderMinimalFallbackPdf(docxBytes);
        }
    }

    /** Overload for renderers that don't use PekReportDocValues (official/internal split). */
    static byte[] convert(byte[] docxBytes) {
        try {
            return convertViaLibreOffice(docxBytes);
        } catch (IOException conversionFailure) {
            log.warn("LibreOffice conversion unavailable, using minimal PDF fallback: {}", conversionFailure.getMessage());
            return renderMinimalFallbackPdf(docxBytes);
        }
    }

    private static byte[] renderMinimalFallbackPdf(byte[] docxBytes) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            com.lowagie.text.Document document = new com.lowagie.text.Document();
            com.lowagie.text.pdf.PdfWriter.getInstance(document, out);
            document.open();
            document.add(new com.lowagie.text.Paragraph("Документ ПЭК (LibreOffice недоступен)"));
            document.add(new com.lowagie.text.Paragraph("Размер DOCX: " + docxBytes.length + " байт"));
            document.close();
            return out.toByteArray();
        } catch (com.lowagie.text.DocumentException e) {
            throw new BadRequestException("Не удалось сформировать резервный PDF: " + e.getMessage());
        }
    }

    private static byte[] convertViaLibreOffice(byte[] docxBytes) throws IOException {
        Path tempDir = Files.createTempDirectory("pek-report-pdf");
        Path docxFile = tempDir.resolve("report.docx");
        Path pdfFile = tempDir.resolve("report.pdf");
        try {
            Files.write(docxFile, docxBytes);
            ProcessBuilder pb = new ProcessBuilder(
                    "libreoffice", "--headless", "--convert-to", "pdf",
                    "--outdir", tempDir.toString(), docxFile.toString());
            pb.redirectErrorStream(true);
            Process process = pb.start();
            boolean finished = process.waitFor(60, TimeUnit.SECONDS);
            if (!finished) {
                process.destroyForcibly();
                throw new IOException("LibreOffice conversion timeout");
            }
            if (Files.exists(pdfFile)) {
                return Files.readAllBytes(pdfFile);
            }
            throw new IOException("PDF file not generated by LibreOffice");
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IOException("PDF conversion interrupted", e);
        } finally {
            try {
                Files.deleteIfExists(pdfFile);
                Files.deleteIfExists(docxFile);
                Files.deleteIfExists(tempDir);
            } catch (IOException ignored) {
            }
        }
    }

    private static byte[] renderFallbackPdf(PekReportDocValues v) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            com.lowagie.text.Document document = new com.lowagie.text.Document();
            com.lowagie.text.pdf.PdfWriter.getInstance(document, out);
            document.open();
            document.add(new com.lowagie.text.Paragraph("Отчёт ПЭК № " + v.reportNumber()));
            document.add(new com.lowagie.text.Paragraph("Версия: " + v.version()));
            document.add(new com.lowagie.text.Paragraph("Компания: " + v.companyName()));
            document.add(new com.lowagie.text.Paragraph("Объект: " + v.objectName()));
            document.add(new com.lowagie.text.Paragraph("Период: " + v.periodStart() + " - " + v.periodEnd()));
            document.add(new com.lowagie.text.Paragraph("Сформировано: " + v.generatedAtLabel()));
            document.close();
            return out.toByteArray();
        } catch (com.lowagie.text.DocumentException e) {
            throw new BadRequestException("Не удалось сформировать PDF отчёта ПЭК: " + e.getMessage());
        }
    }
}
