import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, MenuItem, TextField } from '@mui/material';
import type { PekPermit, PekPermitNormative, PekPermitNormativeRequest } from '../../api/pekContracts';
import { pekApi } from '../../api/pekService';
import { mapPekError } from '../../utils/pekErrorMapper';

const numberOrNull = (value: FormDataEntryValue | null) => value == null || value === '' ? null : Number(value);
export default function PekPermitNormatives({ permit, editable }: { permit: PekPermit; editable: boolean }) {
  const queryClient = useQueryClient();
  const key = ['pek', 'permit', permit.id, 'normatives'];
  const list = useQuery({ queryKey: key, queryFn: ({ signal }) => pekApi.getPermitNormatives(permit.id, signal) });
  const indicators = useQuery({ queryKey: ['pek', 'lookups', 'indicators'], queryFn: ({ signal }) => pekApi.getIndicatorLookup('', 200, signal) });
  const [editing, setEditing] = useState<PekPermitNormative | null>(null);
  const refresh = () => queryClient.invalidateQueries({ queryKey: key });
  const save = useMutation({ mutationFn: (body: PekPermitNormativeRequest) => editing ? pekApi.updatePermitNormative(permit.id, editing.id, editing.version, body) : pekApi.createPermitNormative(permit.id, body), onSuccess: async () => { setEditing(null); await refresh(); } });
  const remove = useMutation({ mutationFn: (id: number) => pekApi.deletePermitNormative(permit.id, id), onSuccess: refresh });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const indicatorId = numberOrNull(data.get('indicatorId')); const indicator = indicators.data?.find((item) => item.id === indicatorId); save.mutate({ sourceType: String(data.get('sourceType') || '') as PekPermitNormativeRequest['sourceType'] || null, sourceId: numberOrNull(data.get('sourceId')), indicatorId, indicatorCode: indicator?.code || String(data.get('indicatorCode') || '') || null, indicatorName: indicator?.name || String(data.get('indicatorName') || ''), comparisonType: String(data.get('comparisonType') || 'LE'), minValue: numberOrNull(data.get('minValue')), maxValue: numberOrNull(data.get('maxValue')), normativeValue: numberOrNull(data.get('normativeValue')), unit: String(data.get('unit') || '') || null, validFrom: String(data.get('validFrom') || '') || null, validTo: String(data.get('validTo') || '') || null, basis: String(data.get('basis') || '') || null }); };
  const error = list.error || save.error || remove.error;
  return <section className="space-y-4 border-t pt-5"><div><h2 className="font-black">Нормативы разрешения</h2><p className="text-sm text-slate-500">Границы нормативов копируются в показатели программы при выборе или автоподборе.</p></div>{error && <Alert severity="error">{mapPekError(error).message}</Alert>}<div className="space-y-2">{list.data?.map((item) => <article key={item.id} className="flex flex-wrap justify-between gap-3 rounded-xl border p-3"><div><b>{item.indicatorName}</b><p className="text-sm text-slate-500">{item.sourceName || 'Всё разрешение'} · {item.comparisonType} · {item.normativeValue ?? `${item.minValue ?? '—'} — ${item.maxValue ?? '—'}`} {item.unit}</p></div>{editable && <div className="flex gap-2"><Button onClick={() => setEditing(item)}>Изменить</Button><Button color="error" onClick={() => remove.mutate(item.id)}>Удалить</Button></div>}</article>)}</div>{editable && <form key={editing?.id || 'new'} className="grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-3" onSubmit={submit}><TextField select name="sourceType" label="Тип источника" defaultValue={editing?.sourceType || ''}><MenuItem value="">Всё разрешение</MenuItem>{['EMISSION_SOURCE', 'WATER_OUTLET', 'WASTE_SOURCE', 'MONITORING_POINT'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField name="sourceId" type="number" label="ID источника" defaultValue={editing?.sourceId || ''} /><TextField select name="indicatorId" label="Показатель" defaultValue={editing?.indicatorId || ''}>{indicators.data?.map((item) => <MenuItem key={item.id} value={item.id}>{item.code} · {item.name}</MenuItem>)}</TextField><TextField name="indicatorName" label="Название показателя" defaultValue={editing?.indicatorName || ''} /><TextField select name="comparisonType" label="Сравнение" defaultValue={editing?.comparisonType || 'LE'}>{['LE', 'GE', 'RANGE', 'INFO', 'EQUAL', 'ABSENT'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField name="normativeValue" type="number" label="Норматив" defaultValue={editing?.normativeValue ?? ''} /><TextField name="minValue" type="number" label="Минимум" defaultValue={editing?.minValue ?? ''} /><TextField name="maxValue" type="number" label="Максимум" defaultValue={editing?.maxValue ?? ''} /><TextField name="unit" label="Единица" defaultValue={editing?.unit || ''} /><TextField name="validFrom" type="date" label="Действует с" InputLabelProps={{ shrink: true }} defaultValue={editing?.validFrom || ''} /><TextField name="validTo" type="date" label="Действует до" InputLabelProps={{ shrink: true }} defaultValue={editing?.validTo || ''} /><TextField name="basis" label="Основание" defaultValue={editing?.basis || ''} /><div className="flex gap-2"><Button type="submit" variant="contained" disabled={save.isPending}>{editing ? 'Сохранить' : 'Добавить норматив'}</Button>{editing && <Button onClick={() => setEditing(null)}>Отмена</Button>}</div></form>}</section>;
}
