import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, TextField } from '@mui/material';
import type { PekPermit, PekPermitCondition, PekPermitRevision } from '../../api/pekContracts';
import { pekApi } from '../../api/pekService';
import { mapPekError } from '../../utils/pekErrorMapper';

const emptyLimit = () => ({ id: null, emissionSourceId: null, dischargeSourceId: null, wasteItemId: null, substanceCode: '', substanceName: '', limitGs: null, limitTonsYear: null, limitMgM3: null, limitMgDm3: null, limitTons: null });
const emptyCondition = (sortOrder: number): PekPermitCondition => ({ id: null, clause: '', conditionType: '', text: '', sortOrder, limits: [emptyLimit()] });
const numberOrNull = (value: string) => value === '' ? null : Number(value);

export default function PekPermitRevisions({ permit, editable }: { permit: PekPermit; editable: boolean }) {
  const queryClient = useQueryClient();
  const key = ['pek', 'permit', permit.id, 'revisions'];
  const revisions = useQuery({ queryKey: key, queryFn: ({ signal }) => pekApi.getPermitRevisions(permit.id, signal) });
  const [selected, setSelected] = useState<PekPermitRevision | null>(null);
  const [conditions, setConditions] = useState<PekPermitCondition[]>([]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: key });
  const select = (revision: PekPermitRevision) => { setSelected(revision); setConditions(revision.conditions.length ? revision.conditions : [emptyCondition(1)]); };
  const create = useMutation({ mutationFn: (body: Parameters<typeof pekApi.createPermitRevision>[1]) => pekApi.createPermitRevision(permit.id, body), onSuccess: async (value) => { await refresh(); select(value); } });
  const save = useMutation({ mutationFn: () => pekApi.replacePermitRevisionConditions(permit.id, selected!.id, selected!.version, conditions), onSuccess: async (value) => { await refresh(); select(value); } });
  const activate = useMutation({ mutationFn: () => pekApi.activatePermitRevision(permit.id, selected!.id, selected!.version), onSuccess: async () => { setSelected(null); await refresh(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ basis: String(data.get('basis') || '') || null, documentNumber: String(data.get('documentNumber') || '') || null, effectiveFrom: String(data.get('effectiveFrom') || '') || null, effectiveTo: String(data.get('effectiveTo') || '') || null }); };
  const changeCondition = (index: number, patch: Partial<PekPermitCondition>) => setConditions((rows) => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const changeLimit = (conditionIndex: number, limitIndex: number, field: string, value: string | number | null) => setConditions((rows) => rows.map((row, i) => i !== conditionIndex ? row : { ...row, limits: row.limits.map((limit, j) => j === limitIndex ? { ...limit, [field]: value } : limit) }));
  const error = revisions.error || create.error || save.error || activate.error;
  return <div className="space-y-4">
    {error && <Alert severity="error">{mapPekError(error).message}</Alert>}
    {revisions.isLoading ? <p>Загрузка редакций…</p> : <div className="space-y-2">{revisions.data?.map((revision) => <button key={revision.id} type="button" onClick={() => select(revision)} className={`w-full rounded-xl border p-3 text-left ${selected?.id === revision.id ? 'border-eco-600 bg-eco-50' : ''}`}><b>Редакция № {revision.revisionNumber}</b> · {revision.status}<span className="block text-sm text-slate-500">{revision.documentNumber || 'без номера'} · {revision.effectiveFrom || '—'} — {revision.effectiveTo || '—'}</span></button>)}</div>}
    {editable && <form className="grid gap-2 border-t pt-4 sm:grid-cols-2" onSubmit={submit}><TextField name="basis" label="Основание" /><TextField name="documentNumber" label="Номер документа" /><TextField name="effectiveFrom" type="date" label="Действует с" InputLabelProps={{ shrink: true }} /><TextField name="effectiveTo" type="date" label="Действует до" InputLabelProps={{ shrink: true }} /><Button type="submit" disabled={create.isPending}>Создать черновик редакции</Button></form>}
    {selected && <section className="space-y-3 border-t pt-4"><div className="flex justify-between gap-2"><h3 className="font-black">Условия редакции № {selected.revisionNumber}</h3>{selected.status === 'DRAFT' && editable && <Button color="success" disabled={activate.isPending} onClick={() => activate.mutate()}>Ввести в действие</Button>}</div>{conditions.map((condition, ci) => <div key={ci} className="space-y-3 rounded-xl border p-3"><div className="grid gap-2 sm:grid-cols-3"><TextField label="Пункт" value={condition.clause} disabled={!editable || selected.status !== 'DRAFT'} onChange={(e) => changeCondition(ci, { clause: e.target.value })} /><TextField label="Тип условия" value={condition.conditionType} disabled={!editable || selected.status !== 'DRAFT'} onChange={(e) => changeCondition(ci, { conditionType: e.target.value })} /><TextField label="Текст" value={condition.text} disabled={!editable || selected.status !== 'DRAFT'} onChange={(e) => changeCondition(ci, { text: e.target.value })} /></div>{condition.limits.map((limit, li) => <div key={li} className="grid gap-2 rounded-lg bg-slate-50 p-2 sm:grid-cols-4"><TextField label="ID источника выброса" type="number" value={limit.emissionSourceId ?? ''} disabled={!editable || selected.status !== 'DRAFT'} onChange={(e) => changeLimit(ci, li, 'emissionSourceId', numberOrNull(e.target.value))} /><TextField label="Код вещества" value={limit.substanceCode || ''} disabled={!editable || selected.status !== 'DRAFT'} onChange={(e) => changeLimit(ci, li, 'substanceCode', e.target.value)} /><TextField label="Вещество" value={limit.substanceName || ''} disabled={!editable || selected.status !== 'DRAFT'} onChange={(e) => changeLimit(ci, li, 'substanceName', e.target.value)} />{(['limitGs', 'limitTonsYear', 'limitMgM3', 'limitMgDm3', 'limitTons'] as const).map((field) => <TextField key={field} label={field} type="number" value={limit[field] ?? ''} disabled={!editable || selected.status !== 'DRAFT'} onChange={(e) => changeLimit(ci, li, field, numberOrNull(e.target.value))} />)}</div>)}{editable && selected.status === 'DRAFT' && <Button onClick={() => changeCondition(ci, { limits: [...condition.limits, emptyLimit()] })}>Добавить лимит</Button>}</div>)}{editable && selected.status === 'DRAFT' && <div className="flex gap-2"><Button onClick={() => setConditions((rows) => [...rows, emptyCondition(rows.length + 1)])}>Добавить условие</Button><Button variant="contained" disabled={save.isPending} onClick={() => save.mutate()}>Сохранить условия</Button></div>}</section>}
  </div>;
}
