import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, MenuItem, TextField } from '@mui/material';
import type { PekProgram, PekSectionApplicability } from '../../api/pekContracts';
import { pekApi } from '../../api/pekService';
import { mapPekError } from '../../utils/pekErrorMapper';

export default function PekProgramRules({ program }: { program: PekProgram }) {
  const queryClient = useQueryClient();
  const key = ['pek', 'program', program.id, 'section-applicability'];
  const sections = useQuery({ queryKey: key, queryFn: ({ signal }) => pekApi.getSectionApplicability(program.id, signal) });
  const snapshots = useQuery({ queryKey: ['pek', 'program', program.id, 'approval-snapshots'], queryFn: ({ signal }) => pekApi.getApprovalSnapshots(program.id, signal) });
  const [rows, setRows] = useState<PekSectionApplicability[]>([]);
  useEffect(() => { if (sections.data) setRows(sections.data); }, [sections.data]);
  const save = useMutation({ mutationFn: () => pekApi.updateSectionApplicability(program.id, program.version, rows.map(({ section, status, reason }) => ({ section, status, reason }))), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['pek'] }); } });
  const apply = useMutation({ mutationFn: () => pekApi.applyProgramNormatives(program.id, program.version), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['pek'] }); } });
  const editable = program.availableActions.edit === true;
  return <div className="space-y-5">
    <section className="space-y-3 rounded-2xl border bg-white p-5"><div><h2 className="font-black">Применимость разделов</h2><p className="text-sm text-slate-500">Неприменимый раздел требует обоснования. Если решение не указано, применимость определяется по содержимому программы.</p></div>{sections.isLoading ? <p>Загрузка…</p> : <div className="space-y-2">{rows.map((row, index) => <div key={row.section} className="grid items-start gap-2 rounded-xl border p-3 md:grid-cols-[1fr_14rem_2fr]"><div><b>{row.label}</b><p className="text-xs text-slate-500">{row.section}{row.hasContent ? ' · раздел содержит данные' : ''}</p></div><TextField select size="small" label="Применимость" value={row.status || ''} disabled={!editable || (row.hasContent && row.status !== 'NOT_APPLICABLE')} onChange={(event) => setRows((current) => current.map((item, i) => i === index ? { ...item, status: (event.target.value || null) as PekSectionApplicability['status'] } : item))}><MenuItem value="">Определяет система</MenuItem><MenuItem value="APPLICABLE">Применим</MenuItem><MenuItem value="NOT_APPLICABLE">Не применим</MenuItem></TextField><TextField size="small" label="Причина неприменимости" required={row.status === 'NOT_APPLICABLE'} disabled={!editable || row.status !== 'NOT_APPLICABLE'} value={row.reason || ''} onChange={(event) => setRows((current) => current.map((item, i) => i === index ? { ...item, reason: event.target.value || null } : item))} /></div>)}</div>}{save.error && <Alert severity="error">{mapPekError(save.error).message}</Alert>}{editable && <Button variant="contained" disabled={save.isPending || rows.some((row) => row.status === 'NOT_APPLICABLE' && !row.reason?.trim())} onClick={() => save.mutate()}>Сохранить применимость</Button>}</section>
    <section className="space-y-3 rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">Нормативы показателей</h2><p className="text-sm text-slate-500">Автоподбор заполняет показатели нормативами из привязанных разрешений.</p></div>{editable && <Button variant="outlined" disabled={apply.isPending} onClick={() => apply.mutate()}>Подобрать нормативы</Button>}</div>{apply.data && <Alert severity={apply.data.unresolved.length ? 'warning' : 'success'}>Подобрано: {apply.data.applied.length}. Не разрешено: {apply.data.unresolved.length}.{apply.data.unresolved.map((item) => ` ${item.indicatorName}: ${item.reason}`).join('; ')}</Alert>}{apply.error && <Alert severity="error">{mapPekError(apply.error).message}</Alert>}</section>
    <section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-black">Снимки утверждения</h2>{snapshots.isLoading ? <p>Загрузка…</p> : !snapshots.data?.length ? <p className="text-sm text-slate-500">Снимок появится после утверждения программы.</p> : <div className="space-y-2">{snapshots.data.map((snapshot) => <details key={snapshot.id} className="rounded-xl border p-3"><summary className="cursor-pointer font-bold">{snapshot.approvedAt} · {snapshot.approvedByName}</summary><div className="mt-2 text-sm text-slate-600"><p>Приказ: {snapshot.regulationCode} / {snapshot.regulationVersion}</p><p>Форма: {snapshot.formVersion} · ревизия {snapshot.contentRevision}</p><p className="break-all">SHA-256: {snapshot.payloadSha256}</p></div></details>)}</div>}</section>
  </div>;
}
