export {
  addComment,
  addAnnualQuarterComment,
  addAnnualQuarterPayment,
  addAnnualQuarterResult,
  assignManager,
  completeAnnualRequest,
  getOrderById,
  getOrders,
  sendContractAndInvoice,
  updateContractStatus,
  updateEcologyStatus,
  updateLaboratoryStatus,
  updateOrderStatus,
  updatePaymentStatus,
  updateAnnualQuarterWorkStatus,
  uploadAnnualQuarterDocument,
  uploadDocument,
} from './orderService';
