import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import Button from '../../../../components/ui/Button';
import Modal from '../../../../components/ui/Modal';
import protocolService from '../../../../services/protocolService';
import type { NormativeRecord, ProtocolTemplateId } from '../../../../types/protocols';

type Props = { open: boolean; templateId: ProtocolTemplateId | ''; onClose: () => void; onAdd: (items: NormativeRecord[]) => void };
const NormativeSelectorModal = ({ open, templateId, onClose, onAdd }: Props) => { const [search,setSearch] = useState(''); const [selected,setSelected] = useState<string[]>([]); const query = useQuery({ queryKey: ['protocol-wizard-normatives',templateId,search], enabled: open && Boolean(templateId), queryFn: ({ signal }) => protocolService.searchNormative({ templateId, search: search.trim(), page: '0', size: '50' }, signal) }); const rows = useMemo(() => query.data?.items || query.data?.normatives || (query.data?.normative ? [query.data.normative] : []), [query.data]); return <Modal open={open} onClose={onClose} size="xl" title="Выбор нормативных показателей" closeOnBackdrop={false} footer={<><Button type="button" variant="secondary" onClick={onClose}>Отмена</Button><Button type="button" disabled={!selected.length} onClick={() => { onAdd(rows.filter((item) => selected.includes(item.id))); setSelected([]); }}>Добавить выбранные ({selected.length})</Button></>}><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Поиск по названию или коду" className="w-full rounded-xl border border-slate-200 px-3 py-2.5" /><div className="mt-4 max-h-[55vh] space-y-2 overflow-y-auto">{rows.map((item) => <label key={item.id} className="flex gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current,item.id] : current.filter((id) => id !== item.id))} /><span><strong>{item.indicator || item.indicatorName || item.name || item.code}</strong><span className="mt-1 block text-xs text-slate-500">{item.code || item.pollutantCode || 'без кода'} · {item.unit || 'без единицы'} · {item.value || item.normativeValue || '—'} · {item.normativeDocument || item.sourceDocumentName || 'источник не указан'}</span></span></label>)}{query.isLoading && <p>Загрузка нормативов…</p>}{query.isError && <p className="text-rose-700">Не удалось загрузить нормативы.</p>}</div></Modal>; };
export default NormativeSelectorModal;
