import { useFieldArray, useFormContext } from 'react-hook-form';
import type { MeasurementDevice } from '../../../../types/protocols';
import { isDeviceValidForDate } from '../../../../utils/protocolDevices';
import ProtocolResultRow from './ProtocolResultRow';
import { CHEMICAL_TYPES, emptyWizardResult, type ProtocolWizardForm } from '../wizardTypes';

type Props = { devices: MeasurementDevice[] };
const ProtocolResultTable = ({ devices }: Props) => { const { control, watch } = useFormContext<ProtocolWizardForm>(); const { fields, append, remove, insert } = useFieldArray({ control, name: 'results' }); const values = watch(); const chemical = Boolean(values.templateId && CHEMICAL_TYPES.has(values.templateId)); return <div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-[1450px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['№','Показатель','Код / фактор','Единица','Результат','Место отбора','Прибор','Норматив','Соответствие','Действия'].map((name) => <th key={name} className="px-2 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{fields.map((field,index) => { const row = values.results[index]; const selected = devices.find((item) => String(item.id) === row?.measurementDeviceId); const invalid = Boolean(row?.measurementDeviceId && (!selected || !isDeviceValidForDate(selected, values.measurementDate))); return <ProtocolResultRow key={field.id} index={index} chemical={chemical} devices={devices} measurementDate={values.measurementDate} laboratoryId={values.laboratoryId} invalidDevice={invalid} onDuplicate={() => insert(index + 1, { ...row })} onRemove={() => remove(index)} />; })}</tbody></table></div><button type="button" onClick={() => append(emptyWizardResult())} className="mt-3 rounded-full border border-eco-300 px-4 py-2 text-sm font-bold text-eco-800 hover:bg-eco-50">Добавить показатель</button></div>; };
export default ProtocolResultTable;
