-- Unifies every CMS content type (news/articles, eco_services, service_city_pages) onto one
-- ContentStatus workflow (DRAFT/IN_REVIEW/APPROVED/PUBLISHED/ARCHIVED) with optimistic locking,
-- and adds the Expert/TrustDocument verification-workflow entities.

-- news: add optimistic locking (V99 already added review_status/author_id/reviewer_id/reviewed_at)
ALTER TABLE news ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- eco_services: retrofit into the same reviewable-content workflow.
ALTER TABLE eco_services ADD COLUMN content_status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED';
ALTER TABLE eco_services ADD COLUMN author_id BIGINT NULL;
ALTER TABLE eco_services ADD COLUMN reviewer_id BIGINT NULL;
ALTER TABLE eco_services ADD COLUMN reviewed_at TIMESTAMP NULL;
ALTER TABLE eco_services ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
-- Pre-existing services were already live - same reasoning as V99 for news: don't silently
-- de-index/hide catalogue services that were already public, only new ones default to DRAFT.

-- service_city_pages: collapse the old (page_status, region_content_status) pair onto one
-- content_status column matching news/eco_services, and add optimistic locking.
ALTER TABLE service_city_pages ADD COLUMN content_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT';
UPDATE service_city_pages SET content_status =
    CASE
        WHEN page_status = 'PUBLISHED' AND region_content_status = 'APPROVED' THEN 'PUBLISHED'
        WHEN region_content_status = 'APPROVED' THEN 'APPROVED'
        WHEN region_content_status = 'REQUIRES_REVIEW' THEN 'IN_REVIEW'
        ELSE 'DRAFT'
    END;
ALTER TABLE service_city_pages DROP COLUMN page_status;
ALTER TABLE service_city_pages DROP COLUMN region_content_status;
ALTER TABLE service_city_pages ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- Experts: named specialists whose credentials/bio back an article's E-E-A-T signal. Only
-- VERIFIED experts may ever be exposed by the public API - see ExpertRepository/ExpertController.
CREATE TABLE content_experts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    position VARCHAR(200),
    credentials VARCHAR(1000),
    bio VARCHAR(2000),
    photo_url VARCHAR(300),
    verification_status VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    verifier_id BIGINT NULL,
    verified_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    version BIGINT NOT NULL DEFAULT 0
);

-- Trust documents: licenses/accreditations/certificates backing a claim of expertise. Only
-- VERIFIED documents may ever be exposed by the public API.
CREATE TABLE content_trust_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(100) NOT NULL,
    document_number VARCHAR(120),
    issued_by VARCHAR(300),
    issued_at DATE,
    valid_until DATE,
    source_url VARCHAR(500),
    verification_status VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    verifier_id BIGINT NULL,
    verified_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    version BIGINT NOT NULL DEFAULT 0
);
