-- AEO structured blocks on eco_services (module fix item 1) - kept as discrete columns/child
-- tables rather than one HTML blob, so the frontend can render each block distinctly.
ALTER TABLE eco_services ADD COLUMN short_answer VARCHAR(500);
ALTER TABLE eco_services ADD COLUMN who_needs VARCHAR(1000);
ALTER TABLE eco_services ADD COLUMN when_required VARCHAR(1000);
ALTER TABLE eco_services ADD COLUMN when_not_required VARCHAR(1000);
ALTER TABLE eco_services ADD COLUMN timeline VARCHAR(500);

CREATE TABLE eco_service_required_documents (
    service_id VARCHAR(80) NOT NULL REFERENCES eco_services(id),
    ord INT NOT NULL,
    item_value VARCHAR(400),
    PRIMARY KEY (service_id, ord)
);

CREATE TABLE eco_service_customer_receives (
    service_id VARCHAR(80) NOT NULL REFERENCES eco_services(id),
    ord INT NOT NULL,
    item_value VARCHAR(400),
    PRIMARY KEY (service_id, ord)
);

CREATE TABLE eco_service_pricing_factors (
    service_id VARCHAR(80) NOT NULL REFERENCES eco_services(id),
    ord INT NOT NULL,
    item_value VARCHAR(400),
    PRIMARY KEY (service_id, ord)
);

CREATE TABLE eco_service_legal_basis (
    service_id VARCHAR(80) NOT NULL REFERENCES eco_services(id),
    ord INT NOT NULL,
    item_value VARCHAR(400),
    PRIMARY KEY (service_id, ord)
);

CREATE TABLE eco_service_common_mistakes (
    service_id VARCHAR(80) NOT NULL REFERENCES eco_services(id),
    ord INT NOT NULL,
    item_value VARCHAR(400),
    PRIMARY KEY (service_id, ord)
);

CREATE TABLE eco_service_faq (
    service_id VARCHAR(80) NOT NULL REFERENCES eco_services(id),
    ord INT NOT NULL,
    question VARCHAR(300),
    answer VARCHAR(2000),
    PRIMARY KEY (service_id, ord)
);

-- CaseStudy CMS (module fix item 2) - unified ContentStatus workflow, same shape as news/
-- eco_services/service_city_pages.
CREATE TABLE content_case_studies (
    id VARCHAR(80) PRIMARY KEY,
    title VARCHAR(240) NOT NULL,
    summary VARCHAR(600) NOT NULL,
    client_label VARCHAR(300),
    service_id VARCHAR(80),
    city_slug VARCHAR(60),
    challenge VARCHAR(4000),
    solution VARCHAR(4000),
    image VARCHAR(300),
    content_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    author_id BIGINT NULL,
    reviewer_id BIGINT NULL,
    reviewed_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE content_case_study_results (
    case_slug VARCHAR(80) NOT NULL REFERENCES content_case_studies(id),
    ord INT NOT NULL,
    item_value VARCHAR(400),
    PRIMARY KEY (case_slug, ord)
);

-- AI crawler access log (Infrastructure item 2) - populated by kz.eco.crawlerlog.CrawlerAccessLogFilter,
-- ordinary user traffic is never written here (see that filter's isKnownAiCrawler check).
CREATE TABLE crawler_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawler_name VARCHAR(40) NOT NULL,
    user_agent VARCHAR(500) NOT NULL,
    request_url VARCHAR(1000) NOT NULL,
    status_code INT NOT NULL,
    response_time_ms BIGINT NOT NULL,
    requested_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_crawler_access_log_name_time ON crawler_access_log (crawler_name, requested_at);

-- GEO referral analytics (Analytics item 2) - kept as a distinct "source" enum, never blended
-- into the generic Google-organic KPI (Analytics item 1: "не смешивать GEO с обычной Google-позицией").
CREATE TABLE geo_referral_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(40) NOT NULL,
    medium VARCHAR(80),
    landing_page VARCHAR(500) NOT NULL,
    sessions INT NOT NULL DEFAULT 0,
    conversions INT NOT NULL DEFAULT 0,
    lead_count INT NOT NULL DEFAULT 0,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    recorded_by BIGINT NULL,
    recorded_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_geo_referral_event_source_period ON geo_referral_event (source, period_start);

-- GEO Query Monitor (Analytics item 3) - manually/API-populated check results, never an automated
-- scraper (see kz.eco.geo.GeoMonitoredQueryService javadoc).
CREATE TABLE geo_monitored_query (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query VARCHAR(300) NOT NULL,
    category VARCHAR(80),
    service_id VARCHAR(80),
    city_slug VARCHAR(60),
    intent VARCHAR(40) NOT NULL,
    last_checked_at TIMESTAMP NULL,
    our_brand_mentioned BOOLEAN NOT NULL DEFAULT FALSE,
    our_url_cited BOOLEAN NOT NULL DEFAULT FALSE,
    checked_by BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE geo_monitored_query_competitors (
    query_id BIGINT NOT NULL REFERENCES geo_monitored_query(id),
    ord INT NOT NULL,
    competitor VARCHAR(200),
    PRIMARY KEY (query_id, ord)
);
