-- Expands PekProgram towards the official Правила №250 structure (module fix item 4). New
-- top-level metadata + five related child sections, none of it folded into pek_programs itself.
-- Non-destructive: existing rows get sane defaults, nobody's real status/workflow state changes -
-- "readiness" for pre-existing programs missing the new sections is a COMPUTED value
-- (PekProgramReadinessService), never a forced status mutation, so nothing already
-- SUBMITTED/APPROVED/ACTIVE is silently knocked back to DRAFT.
ALTER TABLE pek_programs ADD COLUMN regulation_version VARCHAR(120) NOT NULL DEFAULT 'Правила №250 (Приказ МЭГПР РК от 26.05.2023 №250)';
ALTER TABLE pek_programs ADD COLUMN template_version VARCHAR(40) NOT NULL DEFAULT 'legacy';
ALTER TABLE pek_programs ADD COLUMN content_revision BIGINT NOT NULL DEFAULT 0;

-- Monitoring points: physical sampling/observation points under one monitoring direction
-- (pek_program_monitoring is the direction/type level, e.g. "emissions" - this is the concrete
-- point(s) within it, e.g. "source #3, roof vent").
CREATE TABLE pek_monitoring_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitoring_id BIGINT NOT NULL REFERENCES pek_program_monitoring(id),
    program_id BIGINT NOT NULL REFERENCES pek_programs(id),
    name VARCHAR(255) NOT NULL,
    coordinates VARCHAR(120),
    description VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_pek_monitoring_points_monitoring ON pek_monitoring_points (monitoring_id);

-- Internal inspections: the company's own scheduled/actual internal PEK inspections (distinct
-- from a regulator's external check) - Правила №250's "внутренний контроль" requirement.
CREATE TABLE pek_program_internal_inspections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES pek_programs(id),
    planned_date DATE,
    actual_date DATE,
    inspection_type VARCHAR(120),
    findings VARCHAR(2000),
    corrective_action_required BOOLEAN NOT NULL DEFAULT FALSE,
    responsible_user_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_pek_internal_inspections_program ON pek_program_internal_inspections (program_id);

-- Measurement QA/QC: the quality-assurance procedure backing each measured parameter (calibration/
-- verification cadence, not the measurement result itself).
CREATE TABLE pek_program_measurement_qa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES pek_programs(id),
    parameter VARCHAR(255) NOT NULL,
    qa_procedure VARCHAR(2000),
    frequency VARCHAR(120),
    responsible_user_id BIGINT,
    last_check_date DATE,
    next_check_date DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_pek_measurement_qa_program ON pek_program_measurement_qa (program_id);

-- Emergency procedures: what to do / who to call on an environmental incident tied to this
-- program's object.
CREATE TABLE pek_program_emergency_procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES pek_programs(id),
    scenario VARCHAR(255) NOT NULL,
    actions VARCHAR(4000),
    responsible_user_id BIGINT,
    contact_phone VARCHAR(40),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_pek_emergency_procedures_program ON pek_program_emergency_procedures (program_id);

-- Responsibility structure: who holds which PEK-relevant role for this specific program (distinct
-- from the single responsible_user_id/reviewer_user_id/approver_user_id columns on pek_programs
-- itself, which only cover the workflow actors - this is the fuller org-chart-style breakdown
-- Правила №250 expects, e.g. "заведующий лабораторией", "инженер-эколог участка").
CREATE TABLE pek_program_responsibilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES pek_programs(id),
    role_label VARCHAR(255) NOT NULL,
    user_id BIGINT,
    duties VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_pek_program_responsibilities_program ON pek_program_responsibilities (program_id);
