-- Corrective actions as a genuine sub-resource of pek_report_exceedances (distinct from the
-- legacy scalar correctiveAction/dueDate/responsibleUserId fields already on that table, which
-- stay untouched for backward compatibility) - each exceedance can now have any number of
-- individually tracked corrective actions with their own lifecycle and history.
CREATE TABLE pek_exceedance_corrective_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exceedance_id BIGINT NOT NULL REFERENCES pek_report_exceedances(id),
    description VARCHAR(2000) NOT NULL,
    responsible_user_id BIGINT,
    due_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    comment VARCHAR(2000),
    completed_at TIMESTAMP,
    completed_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_pek_corrective_actions_exceedance ON pek_exceedance_corrective_actions (exceedance_id);
