import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { pekKeys } from '../api/pekQueryKeys';
import { pekService } from '../api/pekService';
import type { PekProgramFilters, PekProgramStatus } from '../api/pekContracts';
import { PekLoading, PekPageHeader, PekReadiness, PekState, PekStatusBadge } from '../components/common/PekUi';

const PekProgramsPage = () => {
  const [params, setParams] = useSearchParams();
  const filters: PekProgramFilters = {
    search: params.get('search') || undefined, companyId: Number(params.get('companyId')) || undefined,
    objectId: Number(params.get('objectId')) || undefined, status: (params.get('status') || undefined) as PekProgramStatus | undefined,
    activeOn: params.get('activeOn') || undefined, page: Number(params.get('page')) || 0, size: Number(params.get('size')) || 20,
    sort: params.get('sort') || 'updatedAt,desc',
  };
  const query = useQuery({ queryKey: pekKeys.programs(filters), queryFn: ({ signal }) => pekService.getPrograms(filters, signal), placeholderData: keepPreviousData });
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== 'page') next.set('page', '0'); setParams(next, { replace: true }); };
  return <div className="space-y-5"><PekPageHeader title="Программы ПЭК" description="Планы производственного экологического контроля" actions={<Link to="/staff/pek/programs/new" className="rounded-full bg-eco-600 px-5 py-2.5 text-sm font-bold text-white">Создать программу ПЭК</Link>} />
    <section className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-5"><input aria-label="Поиск" placeholder="Номер или название" value={filters.search || ''} onChange={(event) => update('search', event.target.value)} className="rounded-xl border px-3 py-2"/><input aria-label="Компания" placeholder="Компания" value={params.get('companyId') || ''} onChange={(event) => update('companyId', event.target.value)} className="rounded-xl border px-3 py-2"/><input aria-label="Объект" placeholder="Объект" disabled={!filters.companyId} value={params.get('objectId') || ''} onChange={(event) => update('objectId', event.target.value)} className="rounded-xl border px-3 py-2 disabled:bg-slate-100"/><select aria-label="Статус" value={filters.status || ''} onChange={(event) => update('status', event.target.value)} className="rounded-xl border px-3 py-2"><option value="">Все статусы</option>{['DRAFT','UNDER_REVIEW','RETURNED','APPROVED','ACTIVE','ARCHIVED'].map((item) => <option key={item}>{item}</option>)}</select><input aria-label="Действует на дату" type="date" value={filters.activeOn || ''} onChange={(event) => update('activeOn', event.target.value)} className="rounded-xl border px-3 py-2"/></section>
    {query.isLoading ? <PekLoading /> : query.isError ? <PekState title="Не удалось загрузить программы" retry={() => void query.refetch()} /> : !query.data?.content.length ? <PekState title="Для объекта ещё не создана программа ПЭК" message="Создайте программу, чтобы сформировать план контроля." /> : <><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-50 text-left"><tr>{['Номер','Название','Компания','Объект','Версия','Период','Статус','Ответственный','Готовность','Изменено',''].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{query.data.content.map((item) => <tr key={item.id} className="border-t"><td className="px-4 py-3 font-bold">{item.number}</td><td className="px-4 py-3">{item.name}</td><td className="px-4 py-3">{item.company.name}</td><td className="px-4 py-3">{item.object.name}</td><td className="px-4 py-3">{item.version}</td><td className="px-4 py-3">{item.validFrom} — {item.validUntil}</td><td className="px-4 py-3"><PekStatusBadge status={item.status}/></td><td className="px-4 py-3">{item.responsible?.name || '—'}</td><td className="px-4 py-3"><PekReadiness value={item.readinessPercent || 0}/></td><td className="px-4 py-3">{item.updatedAt || '—'}</td><td className="px-4 py-3"><Link className="font-bold text-eco-700" to={`/staff/pek/programs/${item.id}`}>Открыть</Link></td></tr>)}</tbody></table></div><div className="flex justify-between"><button disabled={!filters.page} onClick={() => update('page', String((filters.page || 0) - 1))}>Назад</button><span>Страница {(filters.page || 0) + 1} из {query.data.totalPages || 1}</span><button disabled={(filters.page || 0) + 1 >= query.data.totalPages} onClick={() => update('page', String((filters.page || 0) + 1))}>Далее</button></div></>}
  </div>;
};
export default PekProgramsPage;
