import { useMutation, useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Button from '../../../components/ui/Button';
import { useToast } from '../../../hooks/useToast';
import { getCompanies, getCompanyObjects } from '../../../services/companyService';
import type { PekPeriodType } from '../api/pekContracts';
import { pekKeys } from '../api/pekQueryKeys';
import { pekService } from '../api/pekService';
import { PekPageHeader, PekState } from '../components/common/PekUi';
import { mapPekError } from '../utils/pekErrorMapper';

const steps=['Компания','Объект','Период','Подтверждение'];const input='mt-1 w-full rounded-xl border border-slate-300 px-3 py-2';
const PekReportCreatePage=()=>{const navigate=useNavigate();const toast=useToast();const [step,setStep]=useState(0);const [search,setSearch]=useState('');const [companyId,setCompanyId]=useState(0);const [objectId,setObjectId]=useState(0);const [periodType,setPeriodType]=useState<PekPeriodType>('QUARTER');const [year,setYear]=useState(new Date().getFullYear());const [quarter,setQuarter]=useState(1);const [programId,setProgramId]=useState(0);
 const companies=useQuery({queryKey:['pek','companies',search],queryFn:({signal})=>getCompanies({page:0,size:20,search:search||undefined,status:'ACTIVE'},signal)});
 const objects=useQuery({queryKey:['company-objects',String(companyId)],queryFn:({signal})=>getCompanyObjects(String(companyId),false,signal),enabled:Boolean(companyId)});
 const contextParams={companyId,objectId,periodType,year,quarter:periodType==='QUARTER'?quarter:undefined};
 const context=useQuery({queryKey:pekKeys.creationContext(contextParams),queryFn:({signal})=>pekService.getReportCreationContext(contextParams,signal),enabled:step===3&&Boolean(companyId&&objectId)});
 const create=useMutation({mutationFn:()=>pekService.createReport({...contextParams,programId:programId||context.data?.selectedProgramId}),retry:false,onSuccess:async(report)=>{toast.success('Отчёт ПЭК создан');if(report.status!=='COLLECTING'){try{await pekService.collectReport(report.id,{version:report.version});}catch(error){toast.warning('Отчёт создан, но сбор данных не запущен',mapPekError(error).message);}}navigate(`/staff/pek/reports/${report.id}`);},onError:error=>{const parsed=mapPekError(error);toast.error(parsed.message,parsed.traceId?`Код обращения: ${parsed.traceId}`:undefined);if(parsed.resourceId)navigate(`/staff/pek/reports/${parsed.resourceId}`);}});
 const canNext=step===0?Boolean(companyId):step===1?Boolean(objectId):true;
 return <div className="space-y-5"><PekPageHeader title="Создание отчёта ПЭК" description={`Шаг ${step+1} из 4 · ${steps[step]}`}/><ol className="grid grid-cols-4 gap-2">{steps.map((x,i)=><li key={x} className={`rounded-xl p-3 text-center text-sm font-bold ${i===step?'bg-eco-700 text-white':'bg-white'}`}>{i+1}. {x}</li>)}</ol><section className="rounded-2xl border bg-white p-5">
 {step===0&&<div><label className="font-bold">Поиск компании<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Название или БИН" className={input}/></label><div className="mt-4 grid gap-2">{companies.data?.items.map(c=><button type="button" key={c.id} onClick={()=>{setCompanyId(Number(c.id));setObjectId(0);}} className={`rounded-xl border p-3 text-left ${companyId===Number(c.id)?'border-eco-600 bg-eco-50':''}`}><strong>{c.name}</strong><span className="ml-2 text-sm text-slate-500">БИН {c.bin}</span></button>)}</div></div>}
 {step===1&&<div className="grid gap-2">{objects.isLoading?<p>Загрузка объектов…</p>:objects.data?.filter(x=>x.status!=='ARCHIVED').map(o=><button type="button" key={o.id} onClick={()=>setObjectId(Number(o.id))} className={`rounded-xl border p-4 text-left ${objectId===Number(o.id)?'border-eco-600 bg-eco-50':''}`}><strong>{o.name}</strong><p className="text-sm text-slate-500">{o.address||'Адрес не указан'} · {o.activityType||'Деятельность не указана'}</p></button>)}{!objects.isLoading&&!objects.data?.length&&<PekState title="У компании нет активных объектов"/>}</div>}
 {step===2&&<div className="grid gap-4 md:grid-cols-3"><label>Период<select value={periodType} onChange={e=>setPeriodType(e.target.value as PekPeriodType)} className={input}><option value="QUARTER">Квартал</option><option value="YEAR">Год</option></select></label><label>Год<input type="number" value={year} onChange={e=>setYear(Number(e.target.value))} className={input}/></label>{periodType==='QUARTER'&&<label>Квартал<select value={quarter} onChange={e=>setQuarter(Number(e.target.value))} className={input}>{[1,2,3,4].map(x=><option key={x} value={x}>{x}</option>)}</select></label>}</div>}
 {step===3&&(context.isLoading?<p>Проверяем программу и период…</p>:context.isError?<PekState title="Не удалось проверить возможность создания" retry={()=>void context.refetch()}/>:context.data&&<div className="space-y-3"><Summary label="Компания" value={context.data.company.name}/><Summary label="Объект" value={context.data.object.name}/><Summary label="Период" value={`${context.data.periodStart} — ${context.data.periodEnd}`}/>{context.data.programs.length===1?<Summary label="Программа" value={`${context.data.programs[0].name}, версия ${context.data.programs[0].version}`}/>:context.data.programs.length>1?<label>Программа<select value={programId} onChange={e=>setProgramId(Number(e.target.value))} className={input}><option value={0}>Выберите программу</option>{context.data.programs.map(p=><option key={p.id} value={p.id}>{p.name} · версия {p.version} · {p.validFrom}—{p.validUntil}</option>)}</select></label>:<PekState title="Для выбранного объекта нет действующей программы ПЭК" message="Сначала создайте программу ПЭК."/>}{context.data.duplicateReportId&&<PekState title="Отчёт за этот период уже существует" retry={()=>navigate(`/staff/pek/reports/${context.data?.duplicateReportId}`)}/>} {context.data.warnings.map(x=><p key={x} className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{x}</p>)}{context.data.blockingReasons.map(x=><p key={x} className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{x}</p>)}</div>)}
 </section><footer className="flex justify-between"><Button variant="secondary" disabled={step===0||create.isPending} onClick={()=>setStep(x=>x-1)}>Назад</Button>{step<3?<Button disabled={!canNext} onClick={()=>setStep(x=>x+1)}>Продолжить</Button>:<Button disabled={create.isPending||!context.data||Boolean(context.data.duplicateReportId||context.data.blockingReasons.length||!context.data.programs.length)||(context.data.programs.length>1&&!programId)} aria-busy={create.isPending} onClick={()=>create.mutate()}>{create.isPending?'Создание…':'Создать и собрать данные'}</Button>}</footer></div>;
};
const Summary=({label,value}:{label:string;value:string})=><div className="flex justify-between rounded-xl bg-slate-50 p-3"><span className="text-slate-500">{label}</span><strong>{value}</strong></div>;
export default PekReportCreatePage;
