import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { Protocol } from '../../../types/protocols';
import { protocolSamplingActsApi } from '../api/protocolSamplingActsApi';

const requiredTemplates = new Set(['ambient_air', 'ambient_air_szz', 'industrial_emissions', 'water', 'soil', 'workplace_air']);
const inputClass = 'w-full rounded-lg border border-slate-300 px-3 py-2';
export default function ProtocolSamplingActsTab({ protocol, editable }: { protocol: Protocol; editable: boolean }) {
  const queryClient = useQueryClient();
  const key = ['protocol', protocol.id, 'sampling-acts'];
  const acts = useQuery({ queryKey: key, queryFn: ({ signal }) => protocolSamplingActsApi.list(String(protocol.id), signal) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: key });
  const add = useMutation({ mutationFn: (request: Parameters<typeof protocolSamplingActsApi.add>[1]) => protocolSamplingActsApi.add(String(protocol.id), request), onSuccess: refresh });
  const remove = useMutation({ mutationFn: (id: number) => protocolSamplingActsApi.remove(String(protocol.id), id), onSuccess: refresh });
  const download = useMutation({ mutationFn: (id: number) => protocolSamplingActsApi.download(String(protocol.id), id), onSuccess: ({ blob, fileName }) => { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = fileName; anchor.click(); URL.revokeObjectURL(url); } });
  const [file, setFile] = useState<File | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!file) return; const data = new FormData(event.currentTarget); add.mutate({ actNumber: String(data.get('actNumber') || '').trim(), samplingDate: String(data.get('samplingDate') || ''), samplingPlace: String(data.get('samplingPlace') || '').trim() || null, sampledBy: String(data.get('sampledBy') || '').trim() || null, customerRepresentative: String(data.get('customerRepresentative') || '').trim() || null, notes: String(data.get('notes') || '').trim() || null, file }); };
  const locked = !editable || protocol.status === 'SIGNED' || protocol.status === 'ARCHIVED';
  return <section className="space-y-4 rounded-2xl border bg-white p-5"><div><h2 className="font-black">Акты отбора проб</h2><p className="text-sm text-slate-500">PDF, JPG или PNG. После подписания протокола состав актов замораживается.</p></div>{requiredTemplates.has(protocol.templateId) && !acts.data?.length && <div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Для этого типа протокола акт отбора обязателен для полного комплекта ПЭК.</div>}{acts.isLoading ? <p>Загрузка…</p> : <div className="space-y-2">{acts.data?.map((act) => <article key={act.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>Акт № {act.actNumber}</b><p className="text-sm text-slate-500">{act.samplingDate} · {act.samplingPlace || 'место не указано'} · {act.fileName}</p><p className="text-xs text-slate-400">SHA-256: {act.sha256}</p></div><div className="flex gap-2"><button className="font-bold text-eco-700" onClick={() => download.mutate(act.id)}>Скачать</button>{!locked && <button className="font-bold text-rose-700" onClick={() => remove.mutate(act.id)}>Удалить</button>}</div></article>)}</div>}{!locked && <form className="grid gap-3 md:grid-cols-2" onSubmit={submit}><input className={inputClass} name="actNumber" required placeholder="Номер акта" /><input className={inputClass} name="samplingDate" required type="date" /><input className={inputClass} name="samplingPlace" placeholder="Место отбора" /><input className={inputClass} name="sampledBy" placeholder="Отбор выполнил" /><input className={inputClass} name="customerRepresentative" placeholder="Представитель заказчика" /><input className={inputClass} name="notes" placeholder="Примечание" /><input className={inputClass} required type="file" accept="application/pdf,image/jpeg,image/png" onChange={(event) => setFile(event.target.files?.[0] || null)} /><button className="rounded-lg bg-eco-700 px-4 py-2 font-bold text-white" disabled={add.isPending}>Прикрепить акт</button></form>}{(add.error || remove.error) && <p className="text-sm font-semibold text-rose-700">{String((add.error || remove.error) instanceof Error ? (add.error || remove.error as Error).message : 'Не удалось выполнить действие')}</p>}</section>;
}
