import { Link } from 'react-router-dom';
import type { ArticleContent, ArticleSection, ExpertProfile, ServiceContent } from '../../content/types';
import { getCatalogService } from '../../content/serviceCatalog';
import { articleContentMap } from '../../content/articles/articleContent';

const card = 'rounded-[22px] border border-slate-200 bg-white p-6 shadow-sm';
const partyLabels = { client: 'Клиент', ecoprogress: 'EcoProgress', government: 'Уполномоченный орган', joint: 'Совместно' };

export const ArticleAuthorCard = ({ expert }: { expert: ExpertProfile }) => <aside className={card} aria-label="Автор материала"><p className="text-xs font-bold uppercase tracking-wide text-eco-500">Материал подготовил</p><h2 className="mt-2 text-lg font-bold text-eco-900">{expert.fullName}</h2><p className="text-sm text-slate-600">{expert.position}</p><p className="mt-3 text-sm leading-6 text-slate-600">{expert.bio}</p></aside>;
export const ArticleReviewerCard = ({ expert }: { expert?: ExpertProfile }) => expert ? <aside className={card} aria-label="Проверяющий специалист"><p className="text-xs font-bold uppercase tracking-wide text-eco-500">Проверил</p><h2 className="mt-2 text-lg font-bold text-eco-900">{expert.fullName}</h2><p className="text-sm text-slate-600">{expert.position}</p></aside> : <aside className={`${card} border-amber-200 bg-amber-50`}><h2 className="font-bold text-amber-900">Материал требует проверки профильным экологом</h2><p className="mt-2 text-sm leading-6 text-amber-800">До проверки материал не отмечается как экспертно подтверждённый.</p></aside>;
export const ArticleSources = ({ sources }: { sources: ArticleContent['sources'] }) => <section><h2 className="text-2xl font-bold text-eco-900">Источники и нормативная проверка</h2><ul className="mt-4 space-y-3">{sources.map((source) => <li key={source.url} className={card}><a href={source.url} target="_blank" rel="noopener noreferrer" className="font-semibold text-eco-700 underline decoration-eco-200 underline-offset-4">{source.title}</a><p className="mt-2 text-xs text-slate-500">Статус утверждений: {source.claimStatus === 'verified' ? 'источник проверен' : source.claimStatus === 'requires-review' ? 'требуется правовая проверка применимости' : 'общая информация'}{source.accessedAt ? ` · просмотрено ${source.accessedAt}` : ''}</p></li>)}</ul></section>;
export const ArticleTableOfContents = ({ sections }: { sections: ArticleSection[] }) => <nav className={`${card} bg-eco-50`} aria-label="Содержание статьи"><h2 className="text-lg font-bold text-eco-900">Содержание</h2><ol className="mt-3 space-y-2 text-sm">{sections.map((section, index) => <li key={section.id}><a href={`#${section.id}`} className="text-eco-700 hover:underline">{index + 1}. {section.title}</a></li>)}</ol></nav>;
export const ArticleChecklist = ({ items }: { items: string[] }) => <div className={`${card} bg-eco-50`}><h3 className="text-lg font-bold text-eco-900">Практический чек-лист</h3><ul className="mt-4 space-y-2">{items.map((item) => <li key={item} className="flex gap-3"><span aria-hidden="true" className="text-eco-600">□</span><span>{item}</span></li>)}</ul></div>;
export const ArticleWarning = ({ children }: { children: string }) => <aside className="rounded-[22px] border border-amber-200 bg-amber-50 p-6 text-sm leading-6 text-amber-900"><strong>Важно:</strong> {children}</aside>;
export const ArticleSteps = ({ items }: { items: Array<{ title: string; description: string }> }) => <ol className="space-y-4">{items.map((item, index) => <li key={item.title} className={card}><span className="text-sm font-bold text-eco-500">Шаг {index + 1}</span><h3 className="mt-1 font-bold text-eco-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></li>)}</ol>;
export const ArticleComparisonTable = ({ headers, rows }: { headers: string[]; rows: string[][] }) => <div className="overflow-x-auto rounded-[22px] border border-slate-200"><table className="min-w-full border-collapse text-left text-sm"><thead className="bg-eco-900 text-white"><tr>{headers.map((header) => <th key={header} scope="col" className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-slate-200">{row.map((cell, cellIndex) => cellIndex === 0 ? <th key={cellIndex} scope="row" className="px-4 py-3 font-semibold text-eco-900">{cell}</th> : <td key={cellIndex} className="px-4 py-3 text-slate-600">{cell}</td>)}</tr>)}</tbody></table></div>;
export const RelatedArticles = ({ slugs }: { slugs: string[] }) => <section><h2 className="text-2xl font-bold text-eco-900">Связанные материалы</h2><div className="mt-4 grid gap-3">{slugs.map((slug) => { const article = articleContentMap.get(slug); return article ? <Link key={slug} to={`/news/${slug}`} className={`${card} font-semibold text-eco-800 hover:border-eco-300`}>Прочитать: {article.title}</Link> : null; })}</div></section>;
export const RelatedServices = ({ slugs, title = 'Вместе с этой услугой часто заказывают' }: { slugs: string[]; title?: string }) => <section><h2 className="text-2xl font-bold text-eco-900">{title}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{slugs.map((slug) => { const service = getCatalogService(slug); return service ? <Link key={slug} to={`/services/${slug}`} className={`${card} font-semibold text-eco-800 hover:border-eco-300`}>Узнать об услуге «{service.title}»</Link> : null; })}</div></section>;
export const ServiceDeliverables = ({ items }: { items: ServiceContent['deliverables'] }) => <section><h2 className="text-3xl font-bold text-eco-900">Что получает клиент</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{items.map((item) => <article key={item.title} className={card}><h3 className="font-bold text-eco-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p>{item.format && <p className="mt-3 text-xs font-semibold text-eco-600">Формат: {item.format}</p>}</article>)}</div></section>;
export const ServiceRequiredDocuments = ({ items }: { items: ServiceContent['requiredDocuments'] }) => <section><h2 className="text-3xl font-bold text-eco-900">Необходимые документы</h2><div className="mt-5 space-y-3">{items.map((item) => <article key={item.title} className={card}><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-eco-900">{item.title}</h3><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.required ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600'}`}>{item.required ? 'обязательно для старта' : 'желательно'}</span></div>{item.description && <p className="mt-2 text-sm text-slate-600">{item.description}</p>}<p className="mt-2 text-xs text-slate-500">Источник: {item.source === 'client' ? 'клиент' : item.source === 'government' ? 'государственный источник' : 'EcoProgress'}</p></article>)}</div></section>;
export const ServiceWorkflow = ({ items }: { items: ServiceContent['workflow'] }) => <section><h2 className="text-3xl font-bold text-eco-900">Этапы работы</h2><ol className="mt-5 space-y-4">{items.map((item) => <li key={item.order} className={card}><div className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-eco-800 text-sm font-bold text-white">{item.order}</span><div><h3 className="font-bold text-eco-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p><p className="mt-3 text-xs font-semibold text-eco-600">Ответственный: {partyLabels[item.responsibleParty]}{item.estimatedDuration ? ` · ${item.estimatedDuration}` : ''}</p>{item.result && <p className="mt-2 text-sm"><strong>Результат:</strong> {item.result}</p>}</div></div></li>)}</ol></section>;
export const ServiceLegalBasis = ({ items }: { items: ServiceContent['legalBasis'] }) => <section><h2 className="text-3xl font-bold text-eco-900">Нормативная основа</h2><div className="mt-5 space-y-3">{items.map((item) => <article key={`${item.title}-${item.number || ''}`} className={card}><h3 className="font-bold text-eco-900">{item.title}</h3><p className="mt-1 text-sm text-slate-600">{[item.number, item.date].filter(Boolean).join(' · ')}</p>{item.note && <p className="mt-3 text-sm leading-6 text-slate-600">{item.note}</p>}{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex text-sm font-semibold text-eco-700 underline">Открыть официальный источник</a>}</article>)}</div></section>;
export const ServicePricingFactors = ({ items }: { items: ServiceContent['pricingFactors'] }) => <section><h2 className="text-3xl font-bold text-eco-900">Что влияет на стоимость</h2><div className="mt-5 grid gap-4 sm:grid-cols-3">{items.map((item) => <article key={item.title} className={card}><h3 className="font-bold text-eco-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></article>)}</div></section>;
export const ServiceExclusions = ({ items }: { items: string[] }) => <section className="rounded-[22px] border border-amber-200 bg-amber-50 p-6"><h2 className="text-2xl font-bold text-amber-950">Что не входит в базовую стоимость</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-6 text-amber-900">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>;
export const RegionalAvailability = ({ availability }: { availability: string }) => <aside className="rounded-[20px] border border-eco-200 bg-eco-50 p-5"><h2 className="text-lg font-bold text-eco-900">Территория и формат работы</h2><p className="mt-2 text-sm leading-6 text-slate-700">{availability}</p><Link to="/regions" className="mt-3 inline-flex text-sm font-semibold text-eco-700 underline">Посмотреть условия по регионам</Link></aside>;
export const ContentLastUpdated = ({ date, requiresReview = false }: { date: string; requiresReview?: boolean }) => <p className="text-sm text-slate-500">Последнее обновление: <time dateTime={date}>{date}</time>{requiresReview ? ' · Материал требует проверки профильным экологом' : ''}</p>;
