import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, MessageSquarePlus } from 'lucide-react';
import { addContentComment, getContentComments, resolveContentComment } from '../../services/contentManagementService';
import type { CmsComment, CmsContentType } from '../../types/contentManagement';

export const ContentCommentsPanel = ({ type, contentId, versionId, canComment }: { type: CmsContentType; contentId: string; versionId?: string; canComment: boolean }) => {
  const [comments, setComments] = useState<CmsComment[]>([]); const [text, setText] = useState(''); const [fieldPath, setFieldPath] = useState(''); const [blocking, setBlocking] = useState(false); const [error, setError] = useState('');
  const load = () => getContentComments(type, contentId).then((items) => setComments(items.filter((comment) => comment.status === 'OPEN'))).catch(() => setError('Комментарии не загружены.'));
  useEffect(() => { void load(); }, [contentId, type]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!versionId || !text.trim()) return; try { const created = await addContentComment(type, contentId, { versionId, fieldPath: fieldPath.trim() || undefined, text: text.trim(), blocking }); setComments((items) => [...items, created]); setText(''); setFieldPath(''); setBlocking(false); } catch { setError('Комментарий не добавлен.'); } };
  const resolve = async (comment: CmsComment) => { try { await resolveContentComment(comment.id); setComments((items) => items.filter((item) => item.id !== comment.id)); } catch { setError('Комментарий не закрыт.'); } };
  return <section className="space-y-4 rounded-2xl bg-white p-6"><h3 className="text-xl font-bold text-eco-900">Открытые замечания</h3>{comments.map((comment) => <article key={comment.id} className={`rounded-xl border p-4 ${comment.blocking ? 'border-rose-300 bg-rose-50' : 'border-slate-200'}`}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{comment.authorName || comment.authorId}{comment.blocking && ' · блокирующее'}</p>{comment.fieldPath && <code className="mt-1 block text-xs">{comment.fieldPath}</code>}<p className="mt-2 text-sm leading-6">{comment.text}</p></div>{canComment && <button type="button" onClick={() => resolve(comment)} className="inline-flex h-fit items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><CheckCircle2 size={16} /> Решено</button>}</div></article>)}{comments.length === 0 && <p className="text-sm text-slate-500">Открытых замечаний нет.</p>}{canComment && <form onSubmit={submit} className="space-y-3 border-t pt-4"><label className="block text-sm font-semibold">Путь поля<input value={fieldPath} onChange={(event) => setFieldPath(event.target.value)} placeholder="pricing.priceFrom" className="mt-1 w-full rounded-xl border p-3" /></label><label className="block text-sm font-semibold">Комментарий<textarea required value={text} onChange={(event) => setText(event.target.value)} rows={3} className="mt-1 w-full rounded-xl border p-3" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={blocking} onChange={(event) => setBlocking(event.target.checked)} /> Блокирует следующий этап</label><button type="submit" disabled={!versionId} className="inline-flex items-center gap-2 rounded-xl bg-eco-900 px-4 py-3 font-semibold text-white disabled:opacity-40"><MessageSquarePlus size={17} /> Добавить</button></form>}{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}</section>;
};
