import { useState } from 'react';
import { Upload } from 'lucide-react';
import { uploadContentFile } from '../../services/contentManagementService';
import type { CmsContentType, CmsFile } from '../../types/contentManagement';

const allowedExtensions = ['jpg', 'jpeg', 'png', 'webp', 'avif', 'svg', 'pdf', 'docx'];
const maxSize = 20 * 1024 * 1024;

export const ContentFileUpload = ({ type, contentId, disabled, onUploaded }: { type: CmsContentType; contentId: string; disabled?: boolean; onUploaded: (file: CmsFile) => void }) => {
  const [file, setFile] = useState<File | null>(null); const [altText, setAltText] = useState(''); const [publicAccess, setPublicAccess] = useState(false); const [state, setState] = useState<'idle' | 'uploading' | 'error'>('idle'); const [error, setError] = useState('');
  const submit = async () => { if (!file) return; const extension = file.name.split('.').pop()?.toLowerCase() || ''; if (!allowedExtensions.includes(extension)) { setError('Недопустимое расширение файла.'); return; } if (file.size > maxSize) { setError('Максимальный размер файла — 20 МБ.'); return; } if (file.type.startsWith('image/') && !altText.trim()) { setError('Для публичного изображения обязателен alt.'); return; } setState('uploading'); setError(''); try { const uploaded = await uploadContentFile(type, contentId, file, { altText: altText.trim() || undefined, publicAccess }); onUploaded(uploaded); setFile(null); setAltText(''); setPublicAccess(false); setState('idle'); } catch { setError('Файл не загружен. Проверьте backend, MIME и антивирусный статус.'); setState('error'); } };
  return <section className="space-y-4 rounded-2xl bg-white p-6"><h3 className="text-xl font-bold text-eco-900">Файлы и изображения</h3><label className="block text-sm font-semibold">Файл<input disabled={disabled || state === 'uploading'} type="file" accept=".jpg,.jpeg,.png,.webp,.avif,.svg,.pdf,.docx" onChange={(event) => setFile(event.target.files?.[0] || null)} className="mt-2 block w-full rounded-xl border p-3" /></label><label className="block text-sm font-semibold">Alt / публичное описание<input disabled={disabled} value={altText} onChange={(event) => setAltText(event.target.value)} className="mt-2 w-full rounded-xl border p-3" /></label><label className="flex items-center gap-3 text-sm"><input disabled={disabled} type="checkbox" checked={publicAccess} onChange={(event) => setPublicAccess(event.target.checked)} /> Публичная обезличенная копия проверена</label>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<button type="button" disabled={disabled || !file || state === 'uploading'} onClick={submit} className="inline-flex items-center gap-2 rounded-xl bg-eco-900 px-4 py-3 font-semibold text-white disabled:opacity-40"><Upload size={17} /> {state === 'uploading' ? 'Загрузка…' : 'Загрузить'}</button></section>;
};
