import { useState } from 'react';
import { GitCompareArrows } from 'lucide-react';
import { compareContentVersions } from '../../services/contentManagementService';
import type { CmsContentType, CmsContentVersion, CmsVersionDiff } from '../../types/contentManagement';

const displayValue = (value: unknown) => typeof value === 'string' ? value : JSON.stringify(value, null, 2);

export const VersionDiffPanel = ({ type, contentId, versions }: { type: CmsContentType; contentId: string; versions: CmsContentVersion[] }) => {
  const [left, setLeft] = useState(''); const [right, setRight] = useState(''); const [diff, setDiff] = useState<CmsVersionDiff | null>(null); const [error, setError] = useState('');
  const compare = async () => { if (!left || !right || left === right) { setError('Выберите две разные версии.'); return; } try { setDiff(await compareContentVersions(type, contentId, left, right)); setError(''); } catch { setError('Сравнение версий недоступно.'); } };
  return <section className="rounded-2xl bg-white p-6 lg:col-span-2"><h3 className="flex items-center gap-2 text-xl font-bold"><GitCompareArrows /> Сравнение версий</h3><div className="mt-4 flex flex-wrap gap-3"><select aria-label="Исходная версия" value={left} onChange={(event) => setLeft(event.target.value)} className="rounded-xl border bg-white p-3"><option value="">Исходная версия</option>{versions.map((version) => <option key={version.id} value={version.id}>v{version.versionNumber}</option>)}</select><select aria-label="Новая версия" value={right} onChange={(event) => setRight(event.target.value)} className="rounded-xl border bg-white p-3"><option value="">Новая версия</option>{versions.map((version) => <option key={version.id} value={version.id}>v{version.versionNumber}</option>)}</select><button type="button" onClick={compare} className="rounded-xl bg-eco-900 px-4 py-3 font-semibold text-white">Сравнить</button></div>{error && <p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}{diff && <div className="mt-5 space-y-3">{diff.fields.map((field) => <article key={field.path} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold"><span className={field.kind === 'ADDED' ? 'text-emerald-700' : field.kind === 'REMOVED' ? 'text-rose-700' : 'text-amber-700'}>{field.kind}</span> · <code>{field.path}</code></p><div className="mt-3 grid gap-3 md:grid-cols-2">{field.kind !== 'ADDED' && <pre className="overflow-auto whitespace-pre-wrap rounded-lg bg-rose-50 p-3 text-xs">{displayValue(field.before)}</pre>}{field.kind !== 'REMOVED' && <pre className="overflow-auto whitespace-pre-wrap rounded-lg bg-emerald-50 p-3 text-xs">{displayValue(field.after)}</pre>}</div></article>)}</div>}</section>;
};
