import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import Button from '../../../../components/ui/Button';
import Modal from '../../../../components/ui/Modal';
import { useToast } from '../../../../hooks/useToast';
import type { PekUnmatchedSource } from '../../api/pekContracts';
import { pekKeys } from '../../api/pekQueryKeys';
import { pekService } from '../../api/pekService';
import { mapPekError } from '../../utils/pekErrorMapper';

const PekUnmatchedSources=({reportId,version,rows,readOnly}:{reportId:number;version:number;rows:PekUnmatchedSource[];readOnly:boolean})=>{const [target,setTarget]=useState<{row:PekUnmatchedSource;mode:'link'|'exclude'}|null>(null);const [reason,setReason]=useState('');const [controlItemId,setControlItemId]=useState('');const toast=useToast();const client=useQueryClient();const mutation=useMutation({mutationFn:()=>target?.mode==='link'?pekService.linkUnmatchedSource(reportId,target.row.id,{version,controlItemId:Number(controlItemId),reason}):pekService.excludeUnmatchedSource(reportId,target?.row.id||0,{version,reason}),retry:false,onSuccess:async()=>{setTarget(null);setReason('');await Promise.all([client.invalidateQueries({queryKey:pekKeys.unmatched(reportId)}),client.invalidateQueries({queryKey:pekKeys.report(reportId)}),client.invalidateQueries({queryKey:pekKeys.planFact(reportId)})]);toast.success('Источник обработан');},onError:e=>toast.error(mapPekError(e).message)});return <div className="space-y-3">{rows.map(row=><article key={row.id} className="rounded-xl border p-4"><div className="grid gap-2 md:grid-cols-3"><div><strong>{row.protocolNumber}</strong><p className="text-sm text-slate-500">{row.date} · {row.point}</p></div><div><strong>{row.indicator}</strong><p className="text-sm">{row.result}</p></div><div><p className="text-sm">{row.reason}</p>{row.suggestedControlItem&&<p className="text-xs text-slate-500">Возможно: {row.suggestedControlItem} ({row.confidenceLabel||'требует проверки'})</p>}</div></div><div className="mt-3 flex flex-wrap gap-2"><Link className="rounded-full border px-4 py-2 text-sm font-bold" to={`/staff/protocols/${row.protocolId}`}>Открыть протокол</Link><Button variant="secondary" disabled={readOnly} onClick={()=>setTarget({row,mode:'link'})}>Указать связь</Button><Button variant="danger" disabled={readOnly} onClick={()=>setTarget({row,mode:'exclude'})}>Исключить с причиной</Button></div></article>)}{!rows.length&&<p className="text-slate-500">Несопоставленных источников нет</p>}<Modal open={Boolean(target)} title={target?.mode==='link'?'Указать связь':'Исключить источник'} onClose={()=>!mutation.isPending&&setTarget(null)} loading={mutation.isPending} footer={<><Button variant="secondary" onClick={()=>setTarget(null)}>Отмена</Button><Button disabled={!reason.trim()||target?.mode==='link'&&!controlItemId} onClick={()=>mutation.mutate()}>Подтвердить</Button></>}><div className="space-y-4">{target?.mode==='link'&&<label>Позиция программы<input value={controlItemId} onChange={e=>setControlItemId(e.target.value)} type="number" className="mt-1 w-full rounded-xl border p-3"/></label>}<label>Причина *<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4} className="mt-1 w-full rounded-xl border p-3"/></label>{target?.mode==='exclude'&&<p className="text-sm text-amber-700">Источник не войдёт в отчёт.</p>}</div></Modal></div>};
export default PekUnmatchedSources;
