import { useState } from 'react';
import { useFieldArray, useFormContext } from 'react-hook-form';
import type { MeasurementDevice, NormativeRecord } from '../../../../types/protocols';
import NormativeSelectorModal from '../components/NormativeSelectorModal';
import ProtocolResultTable from '../components/ProtocolResultTable';
import { emptyWizardResult, type ProtocolWizardForm } from '../wizardTypes';

type Props = { devices: MeasurementDevice[] };
const ResultsStep = ({ devices }: Props) => { const [selector,setSelector] = useState(false); const { control, watch } = useFormContext<ProtocolWizardForm>(); const { append, update } = useFieldArray({ control, name: 'results' }); const form = watch(); const addNormatives = (items: NormativeRecord[]) => items.forEach((item) => { const row = { ...emptyWizardResult(), indicatorName: item.indicator || item.indicatorName || item.name || '', pollutantCode: item.pollutantCode || item.code || '', factorType: item.factorType || '', unit: item.unit || '', normativeId: item.id, normativeValue: String(item.value || item.normativeValue || ''), normativeMin: item.min || String(item.minValue || ''), normativeMax: item.max || String(item.maxValue || ''), comparisonType: item.comparisonType || 'LESS_OR_EQUAL', normativeDocument: item.normativeDocument || item.sourceDocumentName || '', sourceDocumentCode: item.sourceDocumentCode || '', testingMethodNd: item.testingMethod || '' }; const emptyIndex = form.results.findIndex((current) => !current.indicatorName && !current.value); if (emptyIndex >= 0) update(emptyIndex,row); else append(row); }); return <section><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 id="wizard-step-title" tabIndex={-1} className="text-xl font-black">Результаты измерений</h3><p className="mt-1 text-sm text-slate-500">Прибор выбирается непосредственно в строке.</p></div><button type="button" onClick={() => setSelector(true)} className="rounded-full bg-eco-100 px-4 py-2 text-sm font-bold text-eco-800">Выбрать из нормативов</button></div><div className="mt-5"><ProtocolResultTable devices={devices} /></div><NormativeSelectorModal open={selector} templateId={form.templateId} onClose={() => setSelector(false)} onAdd={(items) => { addNormatives(items); setSelector(false); }} /></section>; };
export default ResultsStep;
