import { useEffect, useMemo, useState } from 'react';
import { keepPreviousData, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, RefreshCw, Search, Zap } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import Button from '../components/ui/Button';
import Modal from '../components/ui/Modal';
import ReplaceProtocolModal from '../components/protocols/ReplaceProtocolModal';
import ProtocolList from '../components/protocols/ProtocolList';
import { protocolStatusConfig } from '../config/protocolStatus';
import { PROTOCOL_TYPE_OPTIONS } from '../data/protocolTypeConfig';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../hooks/useToast';
import { getActiveLaboratories, getLaboratoryEmployees } from '../services/laboratorySettingsService';
import { parseApiError } from '../services/apiHelpers';
import protocolService from '../services/protocolService';
import type { Protocol, ProtocolComplianceFilter, ProtocolListQuery, ProtocolStatus, ProtocolTemplateId } from '../types/protocols';
import { canCreateProtocol } from '../utils/protocolPermissions';

const sizes = [10, 20, 50, 100];
const inputClass = 'w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none transition focus:border-eco-500 focus:ring-4 focus:ring-eco-100';
const integer = (value: string | null, fallback: number) => { const parsed = Number(value); return Number.isInteger(parsed) && parsed >= 0 ? parsed : fallback; };
const saveBlob = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); };

const ProtocolsPage = () => {
  const navigate = useNavigate(); const toast = useToast(); const { user } = useAuth(); const queryClient = useQueryClient();
  const [params, setParams] = useSearchParams();
  const page = integer(params.get('page'), 0); const requestedSize = integer(params.get('size'), 20); const size = sizes.includes(requestedSize) ? requestedSize : 20;
  const search = params.get('search') || ''; const status = params.get('status') || ''; const templateId = params.get('templateId') || ''; const subtype = params.get('subtype') || '';
  const laboratoryId = params.get('laboratoryId') || ''; const executorId = params.get('executorId') || ''; const compliance = params.get('compliance') || '';
  const dateFrom = params.get('dateFrom') || ''; const dateTo = params.get('dateTo') || ''; const includeArchived = params.get('includeArchived') === 'true'; const sort = params.get('sort') || 'updatedAt,desc';
  const [searchInput, setSearchInput] = useState(search); const [busyId, setBusyId] = useState(''); const [archiveTarget, setArchiveTarget] = useState<Protocol | null>(null); const [replaceTarget, setReplaceTarget] = useState<Protocol | null>(null);
  const update = (changes: Record<string, string | number | boolean | undefined>) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => { if (value === undefined || value === '' || value === false) next.delete(key); else next.set(key, String(value)); }); setParams(next, { replace: true }); };

  useEffect(() => setSearchInput(search), [search]);
  useEffect(() => { const timer = window.setTimeout(() => { const value = searchInput.trim(); if (value !== search) update({ search: value || undefined, page: 0 }); }, 450); return () => window.clearTimeout(timer); }, [searchInput, search]);
  const laboratoriesQuery = useQuery({ queryKey: ['laboratories', 'protocol-filter'], queryFn: ({ signal }) => getActiveLaboratories(signal) });
  const employeesQuery = useQuery({ queryKey: ['laboratory-employees', laboratoryId], queryFn: () => getLaboratoryEmployees(laboratoryId), enabled: Boolean(laboratoryId) });
  const query = useMemo<ProtocolListQuery>(() => ({ page, size, search: search || undefined, status: status as ProtocolStatus || undefined, templateId: templateId as ProtocolTemplateId || undefined, subtype: subtype || undefined, laboratoryId: laboratoryId ? Number(laboratoryId) : undefined, executorId: executorId ? Number(executorId) : undefined, compliance: compliance as ProtocolComplianceFilter || undefined, dateFrom: dateFrom || undefined, dateTo: dateTo || undefined, sort, includeArchived }), [page, size, search, status, templateId, subtype, laboratoryId, executorId, compliance, dateFrom, dateTo, sort, includeArchived]);
  const protocolsQuery = useQuery({ queryKey: ['protocols', query], queryFn: ({ signal }) => protocolService.getProtocolsPage(query, signal), placeholderData: keepPreviousData });
  const data = protocolsQuery.data; const protocols = data?.items || [];
  useEffect(() => { if (data && data.totalPages > 0 && page >= data.totalPages) update({ page: data.totalPages - 1 }); }, [data?.totalPages, page]);

  const reset = () => { setSearchInput(''); setParams({ page: '0', size: String(size), sort: 'updatedAt,desc' }, { replace: true }); };
  const download = async (protocol: Protocol, kind: 'pdf' | 'docx') => { if (busyId) return; setBusyId(protocol.id); try { const file = kind === 'pdf' ? await protocolService.downloadPdf(protocol.id) : await protocolService.downloadDocx(protocol.id); saveBlob(file.blob, file.fileName || `${protocol.protocolNumber}.${kind}`); } catch (error) { const parsed = parseApiError(error, `Не удалось скачать ${kind.toUpperCase()}`); toast.error(parsed.message); } finally { setBusyId(''); } };
  const archive = async () => { if (!archiveTarget || busyId) return; setBusyId(archiveTarget.id); try { await protocolService.archiveProtocol(archiveTarget.id); setArchiveTarget(null); toast.success('Протокол архивирован'); await queryClient.invalidateQueries({ queryKey: ['protocols'] }); } catch (error) { toast.error(parseApiError(error, 'Не удалось архивировать протокол').message); } finally { setBusyId(''); } };
  const replace = async (reason: string) => { if (!replaceTarget || busyId) return; setBusyId(replaceTarget.id); try { const created = await protocolService.replaceProtocol(replaceTarget.id, reason.trim()); setReplaceTarget(null); navigate(`/staff/protocols/${created.id}`); } catch (error) { toast.error(parseApiError(error, 'Не удалось создать исправленную версию').message); } finally { setBusyId(''); } };
  const hasFilters = Boolean(search || status || templateId || subtype || laboratoryId || executorId || compliance || dateFrom || dateTo || includeArchived);
  const from = data && protocols.length ? data.page * data.size + 1 : 0; const to = data ? data.page * data.size + protocols.length : 0;

  return <div className="space-y-6 pb-10">
    <header className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-wide text-eco-700">Испытательная лаборатория</p><h1 className="mt-1 text-3xl font-black text-slate-950">Протоколы</h1><p className="mt-2 text-sm text-slate-500">Создание, расчёт, утверждение, подписание и документы.</p></div>{canCreateProtocol(user) && <div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={() => navigate('/staff/protocols/create')}><Zap className="h-4 w-4" /> Быстрое создание</Button><Button type="button" onClick={() => navigate('/staff/protocols/new')}><Plus className="h-4 w-4" /> Создать протокол</Button></div>}</header>
    <section className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-4">
      <label className="relative xl:col-span-2"><span className="sr-only">Поиск</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Номер, компания, БИН или объект" className={`${inputClass} pl-10`} /></label>
      <select aria-label="Статус" value={status} onChange={(event) => update({ status: event.target.value, page: 0 })} className={inputClass}><option value="">Все статусы</option>{Object.entries(protocolStatusConfig).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select>
      <select aria-label="Тип протокола" value={templateId} onChange={(event) => update({ templateId: event.target.value, page: 0 })} className={inputClass}><option value="">Все типы</option>{PROTOCOL_TYPE_OPTIONS.map((item) => <option key={item.key} value={item.key === 'water' ? 'water_wastewater' : item.key}>{item.title}</option>)}</select>
      <select aria-label="Лаборатория" value={laboratoryId} onChange={(event) => update({ laboratoryId: event.target.value, executorId: undefined, page: 0 })} className={inputClass}><option value="">Все лаборатории</option>{laboratoriesQuery.data?.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      <select aria-label="Исполнитель" value={executorId} disabled={!laboratoryId} onChange={(event) => update({ executorId: event.target.value, page: 0 })} className={inputClass}><option value="">Все исполнители</option>{employeesQuery.data?.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select>
      <select aria-label="Соответствие" value={compliance} onChange={(event) => update({ compliance: event.target.value, page: 0 })} className={inputClass}><option value="">Любое соответствие</option><option value="COMPLIANT">Соответствует</option><option value="NON_COMPLIANT">Не соответствует</option><option value="NOT_EVALUATED">Не оценено</option></select>
      <select aria-label="Сортировка" value={sort} onChange={(event) => update({ sort: event.target.value, page: 0 })} className={inputClass}><option value="updatedAt,desc">Сначала изменённые</option><option value="protocolDate,desc">Сначала новые</option><option value="protocolDate,asc">Сначала старые</option><option value="protocolNumber,asc">По номеру</option></select>
      <label className="text-sm font-semibold text-slate-700"><span>Период с</span><input type="date" value={dateFrom} onChange={(event) => update({ dateFrom: event.target.value, page: 0 })} className={`${inputClass} mt-1`} /></label><label className="text-sm font-semibold text-slate-700"><span>по</span><input type="date" min={dateFrom} value={dateTo} onChange={(event) => update({ dateTo: event.target.value, page: 0 })} className={`${inputClass} mt-1`} /></label>
      <label className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={includeArchived} onChange={(event) => update({ includeArchived: event.target.checked, page: 0 })} /> Показывать архив</label><Button type="button" variant="secondary" disabled={protocolsQuery.isFetching} onClick={() => protocolsQuery.refetch()}><RefreshCw className={`h-4 w-4 ${protocolsQuery.isFetching ? 'animate-spin' : ''}`} /> Обновить</Button>
    </section>
    {dateFrom && dateTo && dateFrom > dateTo && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800">Дата начала периода не может быть позже даты окончания.</div>}
    {protocolsQuery.isError && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-5"><p className="font-bold text-rose-900">{parseApiError(protocolsQuery.error, 'Не удалось загрузить протоколы').message}</p><Button type="button" variant="secondary" className="mt-3" onClick={() => protocolsQuery.refetch()}>Повторить</Button></div>}
    {!protocolsQuery.isError && !protocolsQuery.isLoading && !protocols.length ? <section className="rounded-2xl border border-slate-200 bg-white p-10 text-center"><h2 className="text-lg font-bold text-slate-900">{hasFilters ? 'По заданным параметрам протоколы не найдены' : includeArchived ? 'Архив протоколов пуст' : 'Протоколы пока не созданы'}</h2>{hasFilters && <Button type="button" variant="secondary" className="mt-4" onClick={reset}>Сбросить фильтры</Button>}</section> : !protocolsQuery.isError && <ProtocolList protocols={protocols} role={user?.role} loading={protocolsQuery.isLoading} busyId={busyId} onOpen={(protocol) => navigate(`/staff/protocols/${protocol.id}`)} onArchive={setArchiveTarget} onReplace={setReplaceTarget} onDownload={download} />}
    {data && protocols.length > 0 && <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span>{data.totalElementsExact === false ? `Показано ${protocols.length}; общее количество недоступно` : `Показано ${from}–${to} из ${data.totalElements}`}</span><select aria-label="Размер страницы" value={size} onChange={(event) => update({ size: Number(event.target.value), page: 0 })} className="rounded-lg border border-slate-200 px-2 py-1">{sizes.map((item) => <option key={item}>{item}</option>)}</select></div><div className="flex items-center gap-2"><Button type="button" variant="secondary" disabled={data.first || protocolsQuery.isFetching} onClick={() => update({ page: Math.max(0, page - 1) })}>Назад</Button><span>Страница {data.page + 1}{data.totalElementsExact !== false && ` из ${Math.max(1, data.totalPages)}`}</span><Button type="button" variant="secondary" disabled={data.last || protocolsQuery.isFetching} onClick={() => update({ page: Math.min(page + 1, Math.max(0, data.totalPages - 1)) })}>Далее</Button></div></div>}
    <Modal open={Boolean(archiveTarget)} loading={busyId === archiveTarget?.id} onClose={() => !busyId && setArchiveTarget(null)} title={`Архивировать протокол «${archiveTarget?.protocolNumber || ''}»?`} size="sm" footer={<><Button type="button" variant="secondary" disabled={Boolean(busyId)} onClick={() => setArchiveTarget(null)}>Отмена</Button><Button type="button" variant="danger" disabled={Boolean(busyId)} onClick={archive}>{busyId ? 'Архивирование…' : 'Архивировать'}</Button></>}><p className="text-sm text-slate-600">Протокол останется доступен только для просмотра и скачивания существующих документов.</p></Modal>
    <ReplaceProtocolModal open={Boolean(replaceTarget)} loading={busyId === replaceTarget?.id} onClose={() => !busyId && setReplaceTarget(null)} onConfirm={replace} />
  </div>;
};

export default ProtocolsPage;
