import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AlertTriangle, BarChart3, CheckCircle2, Clock3, FileSearch, History, Save, Search } from 'lucide-react';
import Button from '../../components/ui/Button';
import BackendFeatureUnavailable from '../../components/ui/BackendFeatureUnavailable';
import LoadingSpinner from '../../components/ui/LoadingSpinner';
import StatusBadge from '../../components/ui/StatusBadge';
import { ContentBlockEditor } from '../../components/content-management/ContentBlockEditor';
import { ContentCommentsPanel } from '../../components/content-management/ContentCommentsPanel';
import { ContentFileUpload } from '../../components/content-management/ContentFileUpload';
import { ContentPreviewPanel } from '../../components/content-management/ContentPreviewPanel';
import { VersionDiffPanel } from '../../components/content-management/VersionDiffPanel';
import { canAccess } from '../../config/permissions';
import { useAuth } from '../../contexts/AuthContext';
import {
  compareContentVersions, getContentAnalytics, getContentDashboard, getContentHistory, getContentItem,
  getContentItems, getContentVersions, runContentWorkflowAction, updateContentItem, validateContentItem,
} from '../../services/contentManagementService';
import type {
  CmsContentBlock, CmsContentDetail, CmsContentStatus, CmsContentSummary, CmsContentType, CmsContentVersion, CmsDashboard,
  CmsStatusHistory, CmsValidationResult, ContentAnalyticsSummary,
} from '../../types/contentManagement';

const typeConfig: Record<CmsContentType, { label: string; path: string }> = {
  SERVICE: { label: 'Услуги', path: 'services' }, ARTICLE: { label: 'Статьи', path: 'articles' }, REGION: { label: 'Регионы', path: 'regions' },
  REGIONAL_PAGE: { label: 'Региональные страницы', path: 'regional-pages' }, CASE: { label: 'Кейсы', path: 'cases' }, EXPERT: { label: 'Эксперты', path: 'experts' },
  TRUST_DOCUMENT: { label: 'Документы доверия', path: 'trust-documents' }, LEGAL_SOURCE: { label: 'Нормативы', path: 'legal-sources' }, REDIRECT: { label: 'Redirects', path: 'redirects' },
};

const statusLabels: Record<CmsContentStatus, string> = {
  DRAFT: 'Черновик', CONTENT_REVIEW: 'Редакторская проверка', EXPERT_REVIEW: 'Проверка эколога', LEGAL_REVIEW: 'Юридическая проверка', SEO_REVIEW: 'SEO-проверка',
  READY_TO_PUBLISH: 'Готово к публикации', SCHEDULED: 'Запланировано', PUBLISHED: 'Опубликовано', OUTDATED: 'Требует актуализации', UNPUBLISHED: 'Снято с публикации',
  ARCHIVED: 'Архив', REJECTED: 'Отклонено',
};

const PageTitle = ({ title, description }: { title: string; description: string }) => <header><h2 className="text-3xl font-bold text-eco-900">{title}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">{description}</p></header>;
const ApiError = () => <BackendFeatureUnavailable title="Content Management API недоступен" description="Frontend не подменяет административные данные локальными моками. Подключите backend endpoints /api/admin/content/*, миграцию и server-side RBAC." />;

export const ContentDashboardPage = () => {
  const [dashboard, setDashboard] = useState<CmsDashboard | null>(null); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  useEffect(() => { getContentDashboard().then(setDashboard).catch(() => setFailed(true)).finally(() => setLoading(false)); }, []);
  if (loading) return <LoadingSpinner />;
  return <div className="space-y-8"><PageTitle title="Контент сайта" description="Публикации, проверки, версии, SEO и актуальность материалов." />{failed || !dashboard ? <ApiError /> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
    ['Опубликованные услуги', dashboard.publishedServices], ['Черновики услуг', dashboard.draftServices], ['Статьи на проверке', dashboard.articlesInReview], ['Просрочена актуализация', dashboard.outdatedMaterials],
    ['SEO-ошибки', dashboard.seoErrors], ['Битые ссылки', dashboard.brokenLinks], ['Слабые регионы', dashboard.weakRegionalPages], ['Запланировано', dashboard.scheduledPublications],
  ].map(([label, value]) => <article key={String(label)} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-eco-900">{value}</p></article>)}</div><section className="rounded-2xl bg-white p-6"><h3 className="text-xl font-bold text-eco-900">Последние изменения</h3><div className="mt-4 space-y-3">{dashboard.recentChanges.map((item) => <div key={item.id} className="border-t border-slate-100 pt-3 text-sm"><strong>{item.changedByName || item.changedBy}</strong> · {statusLabels[item.toStatus]} · <time dateTime={item.changedAt}>{item.changedAt}</time></div>)}</div></section></>}</div>;
};

export const ContentListPage = ({ type }: { type: CmsContentType }) => {
  const [items, setItems] = useState<CmsContentSummary[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  useEffect(() => { const handle = window.setTimeout(() => { setLoading(true); setFailed(false); getContentItems({ type, query: query || undefined, status: status as CmsContentStatus || undefined, size: 50 }).then((page) => setItems(page.items)).catch(() => setFailed(true)).finally(() => setLoading(false)); }, 350); return () => window.clearTimeout(handle); }, [query, status, type]);
  const config = typeConfig[type];
  return <div className="space-y-7"><PageTitle title={config.label} description="Список получает только административные DTO backend и не использует публичный fallback." /><div className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-2"><label className="text-sm font-semibold">Поиск<div className="relative mt-2"><Search className="absolute left-3 top-3 text-slate-400" size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-3" /></div></label><label className="text-sm font-semibold">Статус<select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3"><option value="">Все</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{loading ? <LoadingSpinner /> : failed ? <ApiError /> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Название', 'Slug', 'Статус', 'Версия', 'Изменено', 'SEO', ''].map((label) => <th key={label} scope="col" className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-slate-100"><th scope="row" className="px-4 py-3 font-semibold text-eco-900">{item.title}</th><td className="px-4 py-3">{item.slug}</td><td className="px-4 py-3"><StatusBadge status={statusLabels[item.status]} /></td><td className="px-4 py-3">v{item.versionNumber}</td><td className="px-4 py-3">{item.updatedAt}</td><td className="px-4 py-3">{item.validationErrors ? `${item.validationErrors} ошибок` : item.validationWarnings ? `${item.validationWarnings} предупреждений` : 'OK'}</td><td className="px-4 py-3"><Link className="font-semibold text-eco-700 underline" to={`/staff/content/${config.path}/${item.id}`}>Открыть</Link></td></tr>)}</tbody></table>{items.length === 0 && <p className="p-6 text-slate-500">Материалы не найдены.</p>}</div>}</div>;
};

const getNestedString = (payload: Record<string, unknown>, path: string[]) => { let current: unknown = payload; for (const part of path) current = typeof current === 'object' && current !== null ? (current as Record<string, unknown>)[part] : undefined; return typeof current === 'string' ? current : ''; };
const setNestedString = (payload: Record<string, unknown>, path: string[], value: string): Record<string, unknown> => { const result = structuredClone(payload); let current = result; path.forEach((part, index) => { if (index === path.length - 1) current[part] = value; else { const next = current[part]; current[part] = typeof next === 'object' && next !== null && !Array.isArray(next) ? { ...(next as Record<string, unknown>) } : {}; current = current[part] as Record<string, unknown>; } }); return result; };
const getContentBlocks = (payload: Record<string, unknown>): CmsContentBlock[] => Array.isArray(payload.blocks) ? payload.blocks as CmsContentBlock[] : [];

export const ContentEditorPage = ({ type }: { type: CmsContentType }) => {
  const { id = '' } = useParams(); const { user } = useAuth(); const editable = canAccess(user?.role, 'edit_content') || canAccess(user?.role, 'manage_content');
  const [item, setItem] = useState<CmsContentDetail | null>(null); const [initial, setInitial] = useState(''); const [tab, setTab] = useState('main'); const [state, setState] = useState<'loading' | 'saved' | 'saving' | 'error' | 'conflict'>('loading'); const [versions, setVersions] = useState<CmsContentVersion[]>([]); const [history, setHistory] = useState<CmsStatusHistory[]>([]); const [validation, setValidation] = useState<CmsValidationResult | null>(null); const saveSequence = useRef(0);
  useEffect(() => { getContentItem(type, id).then((value) => { setItem(value); setInitial(JSON.stringify(value)); setState('saved'); }).catch(() => setState('error')); }, [id, type]);
  useEffect(() => { if (!item || !editable || state === 'loading' || JSON.stringify(item) === initial) return; const handle = window.setTimeout(async () => { const sequence = ++saveSequence.current; setState('saving'); try { const saved = await updateContentItem(item, 'Автосохранение из CRM'); if (sequence !== saveSequence.current) return; setItem(saved); setInitial(JSON.stringify(saved)); setState('saved'); } catch (error) { if (sequence !== saveSequence.current) return; const statusCode = typeof error === 'object' && error !== null && 'response' in error ? (error as { response?: { status?: number } }).response?.status : undefined; setState(statusCode === 409 ? 'conflict' : 'error'); } }, 1000); return () => window.clearTimeout(handle); }, [editable, initial, item, state]);
  useEffect(() => { if (tab !== 'history' || !id) return; Promise.all([getContentVersions(type, id), getContentHistory(type, id)]).then(([nextVersions, nextHistory]) => { setVersions(nextVersions); setHistory(nextHistory); }).catch(() => undefined); }, [id, tab, type]);
  useEffect(() => { if (!item || !editable || JSON.stringify(item) === initial) return; const warn = (event: BeforeUnloadEvent) => event.preventDefault(); window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [editable, initial, item]);
  if (state === 'loading') return <LoadingSpinner />; if (!item) return <ApiError />;
  const contentPaths = type === 'SERVICE' ? [["hero", "subtitle"], ["summary", "shortDescription"], ["summary", "clientResult"]] : type === 'ARTICLE' ? [["description"], ["excerpt"], ["shortAnswer"]] : [["introduction"], ["description"]];
  const runValidation = () => validateContentItem(type, id).then(setValidation).catch(() => setState('error'));
  const workflow = async (action: 'submit-content-review' | 'approve-expert' | 'approve-legal' | 'approve-seo' | 'publish') => { const comment = window.prompt('Комментарий обязателен для истории статуса'); if (!comment?.trim()) return; try { const updated = await runContentWorkflowAction(type, id, action, { comment }); setItem(updated); setInitial(JSON.stringify(updated)); } catch { setState('error'); } };
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><PageTitle title={item.title} description={`${typeConfig[type].label} · ${item.slug} · версия ${item.versionNumber}`} /><div className="flex items-center gap-2 text-sm">{state === 'saving' ? <><Clock3 size={16} /> Сохранение</> : state === 'saved' ? <><CheckCircle2 className="text-emerald-600" size={16} /> Сохранено</> : state === 'conflict' ? <span className="text-rose-700">Материал изменён другим пользователем. Обновите страницу и сравните версии.</span> : <span className="text-rose-700">Ошибка сохранения</span>}</div></div><nav className="flex flex-wrap gap-2" aria-label="Разделы редактора">{[['main','Основное'],['content','Контент'],['files','Файлы'],['seo','SEO'],['preview','Preview'],['review','Проверка'],['history','История']].map(([value,label]) => <button type="button" key={value} onClick={() => setTab(value)} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab === value ? 'bg-eco-900 text-white' : 'bg-white text-eco-800'}`}>{label}</button>)}</nav>
  {tab === 'main' && <section className="grid gap-4 rounded-2xl bg-white p-6 sm:grid-cols-2"><label className="text-sm font-semibold">Название<input disabled={!editable} value={item.title} onChange={(event) => setItem({ ...item, title: event.target.value })} className="mt-2 w-full rounded-xl border p-3 disabled:bg-slate-100" /></label><label className="text-sm font-semibold">Slug<input disabled={!editable || !canAccess(user?.role, 'review_content_seo')} value={item.slug} onChange={(event) => setItem({ ...item, slug: event.target.value })} className="mt-2 w-full rounded-xl border p-3 disabled:bg-slate-100" /></label><label className="flex items-center gap-3 text-sm font-semibold"><input disabled={!editable} type="checkbox" checked={item.isActive} onChange={(event) => setItem({ ...item, isActive: event.target.checked })} /> Активен</label><label className="flex items-center gap-3 text-sm font-semibold"><input disabled={!editable} type="checkbox" checked={item.indexAllowed} onChange={(event) => setItem({ ...item, indexAllowed: event.target.checked })} /> Разрешена индексация</label></section>}
  {tab === 'content' && <section className="space-y-4 rounded-2xl bg-white p-6">{contentPaths.map((path) => <label key={path.join('.')} className="block text-sm font-semibold">{path.join('.')}<textarea disabled={!editable} value={getNestedString(item.payload, path)} onChange={(event) => setItem({ ...item, payload: setNestedString(item.payload, path, event.target.value) })} rows={5} className="mt-2 w-full rounded-xl border p-3 disabled:bg-slate-100" /></label>)}{type === 'ARTICLE' && <ContentBlockEditor disabled={!editable} blocks={getContentBlocks(item.payload)} onChange={(blocks) => setItem({ ...item, payload: { ...item.payload, blocks } })} />}</section>}
  {tab === 'files' && <ContentFileUpload type={type} contentId={id} disabled={!editable} onUploaded={(file) => { const current = Array.isArray(item.payload.fileIds) ? item.payload.fileIds.filter((value): value is string => typeof value === 'string') : []; setItem({ ...item, payload: { ...item.payload, fileIds: [...current, file.id] } }); }} />}
  {tab === 'seo' && <section className="space-y-4 rounded-2xl bg-white p-6">{(['title','description','canonical'] as const).map((field) => <label key={field} className="block text-sm font-semibold">{field}<input disabled={!canAccess(user?.role, 'review_content_seo') && !canAccess(user?.role, 'manage_content')} value={item.seo[field]} onChange={(event) => setItem({ ...item, seo: { ...item.seo, [field]: event.target.value } })} className="mt-2 w-full rounded-xl border p-3 disabled:bg-slate-100" /></label>)}<label className="block text-sm font-semibold">robots<select disabled={!canAccess(user?.role, 'review_content_seo') && !canAccess(user?.role, 'manage_content')} value={item.seo.robots} onChange={(event) => setItem({ ...item, seo: { ...item.seo, robots: event.target.value as CmsContentDetail['seo']['robots'] } })} className="mt-2 w-full rounded-xl border bg-white p-3"><option>index,follow</option><option>noindex,follow</option><option>noindex,nofollow</option></select></label></section>}
  {tab === 'preview' && <ContentPreviewPanel item={item} />}
  {tab === 'review' && <div className="space-y-5"><section className="space-y-5 rounded-2xl bg-white p-6"><div className="flex flex-wrap gap-2"><Button onClick={runValidation}><FileSearch size={17} /> Проверить</Button>{canAccess(user?.role, 'edit_content') && <Button variant="secondary" onClick={() => workflow('submit-content-review')}>На проверку</Button>}{canAccess(user?.role, 'review_content_expert') && <Button variant="secondary" onClick={() => workflow('approve-expert')}>Подтвердить экологом</Button>}{canAccess(user?.role, 'review_content_legal') && <Button variant="secondary" onClick={() => workflow('approve-legal')}>Подтвердить юристом</Button>}{canAccess(user?.role, 'review_content_seo') && <Button variant="secondary" onClick={() => workflow('approve-seo')}>Подтвердить SEO</Button>}{canAccess(user?.role, 'publish_content') && <Button onClick={() => workflow('publish')}>Опубликовать</Button>}</div>{validation && <div className="grid gap-4 lg:grid-cols-2"><div><h3 className="font-bold text-rose-800">Ошибки: {validation.errors.length}</h3>{validation.errors.map((entry) => <p key={`${entry.code}-${entry.field}`} className="mt-2 text-sm">{entry.field && `${entry.field}: `}{entry.message}</p>)}</div><div><h3 className="font-bold text-amber-800">Предупреждения: {validation.warnings.length}</h3>{validation.warnings.map((entry) => <p key={`${entry.code}-${entry.field}`} className="mt-2 text-sm">{entry.message}</p>)}</div></div>}</section><ContentCommentsPanel type={type} contentId={id} versionId={item.draftVersionId || item.publishedVersionId} canComment={editable || canAccess(user?.role, 'review_content_expert') || canAccess(user?.role, 'review_content_legal') || canAccess(user?.role, 'review_content_seo')} /></div>}
  {tab === 'history' && <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl bg-white p-6"><h3 className="flex items-center gap-2 text-xl font-bold"><History /> Версии</h3>{versions.map((version) => <p key={version.id} className="mt-3 border-t pt-3 text-sm">v{version.versionNumber} · {version.status} · {version.createdByName || version.createdBy}</p>)}</div><div className="rounded-2xl bg-white p-6"><h3 className="text-xl font-bold">Статусы</h3>{history.map((entry) => <p key={entry.id} className="mt-3 border-t pt-3 text-sm">{entry.fromStatus || '—'} → {entry.toStatus} · {entry.comment}</p>)}</div><VersionDiffPanel type={type} contentId={id} versions={versions} /></section>}
  {!editable && <p className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Режим просмотра: backend permission на редактирование отсутствует.</p>}</div>;
};

export const ContentAnalyticsPage = () => { const [data, setData] = useState<ContentAnalyticsSummary | null>(null); const [failed, setFailed] = useState(false); useEffect(() => { getContentAnalytics({}).then(setData).catch(() => setFailed(true)); }, []); return <div className="space-y-7"><PageTitle title="Аналитика контента" description="Агрегаты рассчитываются backend; выручка и статусы договоров не вычисляются в браузере." />{failed || !data ? <ApiError /> : <><div className="grid gap-4 sm:grid-cols-3">{[['Просмотры',data.views],['CTA',data.ctaClicks],['Заявки',data.formSubmits]].map(([label,value]) => <article key={String(label)} className="rounded-2xl bg-white p-5"><p>{label}</p><strong className="mt-2 block text-3xl">{value}</strong></article>)}</div><section className="rounded-2xl bg-white p-6"><h3 className="flex items-center gap-2 text-xl font-bold"><BarChart3 /> Воронка</h3>{data.funnel.map((stage) => <div key={stage.stage} className="mt-4 grid grid-cols-[1fr_auto] gap-3 border-t pt-3"><span>{stage.stage}</span><strong>{stage.value}{stage.conversionFromPrevious !== undefined ? ` · ${stage.conversionFromPrevious}%` : ''}</strong></div>)}</section></>}</div>; };

export const ContentAuditPage = () => <div className="space-y-7"><PageTitle title="Аудит контента" description="Запуск серверной валидации публикаций, проверка SEO, ссылок, нормативов и сроков актуальности." /><ApiError /></div>;
