import { useMemo, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import type { PekOfficialEmissionResultRow, PekOfficialReportData, PekOfficialResultRow, PekOfficialTables, PekOfficialWastewaterResultRow, PekReadinessResponse } from '../../api/pekContracts';

type TableKey = keyof PekOfficialTables;
type Column<T> = { label: string; value: (row: T) => ReactNode };
const tableNames: Record<TableKey, string> = { emissions: 'Выбросы', instrumentalMeasurements: 'Инструментальные измерения', calculatedEmissions: 'Расчётные выбросы', ambientAir: 'Атмосферный воздух', wastewater: 'Сточные воды', water: 'Водные ресурсы', soil: 'Почва', radiation: 'Радиация', marine: 'Морской мониторинг' };
const applicabilityCodes: Record<TableKey, string> = { emissions: 'EMISSIONS', instrumentalMeasurements: 'INSTRUMENTAL_MEASUREMENTS', calculatedEmissions: 'CALCULATED_EMISSIONS', ambientAir: 'AMBIENT_AIR', wastewater: 'WASTEWATER', water: 'WATER', soil: 'SOIL', radiation: 'RADIATION', marine: 'MARINE' };
const text = (value: string | number | null | undefined) => value == null || value === '' ? '—' : String(value);
const exceedance = (value: boolean) => value ? <span className="font-bold text-rose-700">Да</span> : 'Нет';
const protocol = (id: number | null, resultId: number | null, number?: string | null) => id ? <Link className="font-bold text-eco-700 underline" to={`/staff/protocols/${id}`}>{number || `№${id}`}{resultId ? ` · результат ${resultId}` : ''}</Link> : '—';

const emissionColumns: Column<PekOfficialEmissionResultRow>[] = [
  { label: 'Источник', value: row => text(row.sourceName) }, { label: 'Вещество', value: row => text(row.indicatorName) }, { label: 'Норматив г/с', value: row => text(row.normativeGs) }, { label: 'Норматив т/год', value: row => text(row.normativeTonsYear) }, { label: 'Факт г/с', value: row => text(row.actualGs) }, { label: 'Факт т/квартал', value: row => text(row.actualTonsQuarter) }, { label: 'Факт т/год', value: row => text(row.actualTonsYear) }, { label: 'Превышение', value: row => exceedance(row.exceedance) }, { label: 'Корректирующее действие', value: row => text(row.correctiveAction) }, { label: 'Протокол', value: row => protocol(row.protocolId, row.protocolResultId) },
];
const resultColumns: Column<PekOfficialResultRow>[] = [
  { label: 'Точка', value: row => text(row.pointName) }, { label: 'Показатель', value: row => text(row.indicatorName) }, { label: 'Дата', value: row => text(row.measurementDate) }, { label: 'Метод', value: row => text(row.measurementMethod) }, { label: 'Норматив', value: row => text(row.normativeValue) }, { label: 'Факт', value: row => text(row.actualValue) }, { label: 'Единица', value: row => text(row.unit) }, { label: 'Превышение', value: row => exceedance(row.exceedance) }, { label: 'Кратность', value: row => text(row.exceedanceRatio) }, { label: 'Корректирующее действие', value: row => text(row.correctiveAction) }, { label: 'Протокол', value: row => protocol(row.protocolId, row.protocolResultId, row.protocolNumber) },
];
const wastewaterColumns: Column<PekOfficialWastewaterResultRow>[] = [
  { label: 'Выпуск/точка', value: row => text(row.outletName) }, { label: 'Вещество', value: row => text(row.indicatorName) }, { label: 'Норматив', value: row => text(row.normativeValue) }, { label: 'Единица норматива', value: row => text(row.normativeUnit) }, { label: 'Норматив т/год', value: row => text(row.normativeTonsYear) }, { label: 'Факт', value: row => text(row.actualValue) }, { label: 'Факт т/квартал', value: row => text(row.actualTonsQuarter) }, { label: 'Факт т/год', value: row => text(row.actualTonsYear) }, { label: 'Превышение', value: row => exceedance(row.exceedance) }, { label: 'Корректирующее действие', value: row => text(row.correctiveAction) }, { label: 'Протокол', value: row => protocol(row.protocolId, row.protocolResultId) },
];

const OfficialTable = <T extends { exceedance: boolean }>({ tableKey, rows, columns, attention }: { tableKey: TableKey; rows: T[]; columns: Column<T>[]; attention: boolean }) => {
  const [search, setSearch] = useState('');
  const filtered = useMemo(() => rows.filter(row => JSON.stringify(row).toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru'))), [rows, search]);
  const exceedances = rows.filter(row => row.exceedance).length;
  return <section id={`official-${tableKey}`} className="scroll-mt-16 border border-slate-300 bg-white"><div className="flex flex-wrap items-center gap-3 border-b bg-slate-50 px-3 py-2"><h3 className="mr-auto font-black">{tableNames[tableKey]}</h3><span className={`text-xs font-bold ${attention || !rows.length ? 'text-amber-700' : 'text-emerald-700'}`}>{attention || !rows.length ? 'Требует внимания' : 'Готово'}</span><span className="text-xs">Строк: {rows.length}</span><span className={exceedances ? 'text-xs font-bold text-rose-700' : 'text-xs'}>Превышений: {exceedances}</span><input aria-label={`Поиск: ${tableNames[tableKey]}`} value={search} onChange={event => setSearch(event.target.value)} placeholder="Поиск" className="h-8 w-44 border border-slate-300 px-2 text-sm" /></div>
    {!rows.length ? <p className="p-3 text-sm text-slate-500">Нет данных. Состояние готовности определяется проверкой backend.</p> : <div className="max-h-[520px] overflow-auto"><table className="min-w-full border-collapse text-xs"><thead className="sticky top-0 z-10 bg-slate-100"><tr>{columns.map(column => <th key={column.label} className="whitespace-nowrap border-b border-r px-2 py-2 text-left">{column.label}</th>)}</tr></thead><tbody>{filtered.map((row, index) => <tr key={index} className="hover:bg-eco-50">{columns.map(column => <td key={column.label} className="max-w-72 border-b border-r px-2 py-1.5">{column.value(row)}</td>)}</tr>)}</tbody></table>{!filtered.length && <p className="p-3 text-sm text-slate-500">По запросу ничего не найдено.</p>}</div>}
  </section>;
};

const PekOfficialReport = ({ data, readiness }: { data: PekOfficialReportData; readiness?: PekReadinessResponse }) => {
  const officialIssues = readiness?.issues.filter(issue => issue.section === 'OFFICIAL_TABLES') || [];
  const applicable = (key: TableKey) => data.applicability.find(item => item.tableType === applicabilityCodes[key]);
  return <div className="space-y-4">{officialIssues.length > 0 && <section role="alert" className="border border-amber-300 bg-amber-50 p-3"><h3 className="font-black">Официальный отчёт требует внимания</h3><ul className="mt-1 list-disc pl-5 text-sm">{officialIssues.map((issue, index) => <li key={`${issue.code}-${index}`}>{issue.message}</li>)}</ul></section>}
    <section className="grid gap-x-5 gap-y-2 border border-slate-300 bg-white p-3 sm:grid-cols-2 lg:grid-cols-4">{[['Компания', data.general.companyName], ['Объект', data.general.objectName], ['БИН', data.general.companyBin], ['КАТО', data.general.kato], ['Координаты', data.general.coordinates], ['ОКЭД', data.general.oked], ['Категория', data.general.environmentalCategory], ['Проектная мощность', data.general.designCapacity], ['Фактическая мощность', [data.general.actualCapacity, data.general.actualCapacityUnit].filter(Boolean).join(' ')], ['Период', [data.general.periodStart, data.general.periodEnd].filter(Boolean).join(' — ')], ['regulationVersion', data.general.regulationVersion], ['templateVersion', data.general.templateVersion]].map(([label, value]) => <div key={label}><div className="text-[11px] font-bold uppercase text-slate-500">{label}</div><div className="font-semibold">{value || '—'}</div></div>)}</section>
    <section className="border border-slate-300 bg-white p-3"><h3 className="mb-2 font-black">Лаборатория на момент формирования отчёта</h3>{data.laboratory ? <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[['Название', data.laboratory.laboratoryName], ['БИН', data.laboratory.laboratoryBin], ['Аттестат', data.laboratory.accreditationNumber], ['Действует с', data.laboratory.accreditationValidFrom], ['Действует до', data.laboratory.accreditationValidUntil], ['Область аккредитации', data.laboratory.accreditationScope]].map(([label, value]) => <div key={label}><span className="text-xs text-slate-500">{label}: </span><b>{value || '—'}</b></div>)}</div> : <p className="text-sm text-slate-500">Snapshot лаборатории отсутствует.</p>}</section>
    {(Object.keys(tableNames) as TableKey[]).map(key => { const rule = applicable(key); if (!rule?.applicable) return <section key={key} className="flex border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><b>{tableNames[key]}</b><span className="ml-auto text-slate-500">Не применяется{rule?.reason ? `: ${rule.reason}` : ''}</span></section>; const attention = officialIssues.length > 0; if (key === 'emissions' || key === 'calculatedEmissions') return <OfficialTable key={key} tableKey={key} rows={data.tables[key]} columns={emissionColumns} attention={attention} />; if (key === 'wastewater' || key === 'marine') return <OfficialTable key={key} tableKey={key} rows={data.tables[key]} columns={wastewaterColumns} attention={attention} />; return <OfficialTable key={key} tableKey={key} rows={data.tables[key]} columns={resultColumns} attention={attention} />; })}
  </div>;
};
export default PekOfficialReport;
