CREATE TABLE content_cities (
    slug VARCHAR(60) PRIMARY KEY,
    nominative VARCHAR(80) NOT NULL,
    genitive VARCHAR(80) NOT NULL,
    dative VARCHAR(80) NOT NULL,
    accusative VARCHAR(80) NOT NULL,
    instrumental VARCHAR(80) NOT NULL,
    prepositional VARCHAR(80) NOT NULL,
    region_name VARCHAR(120)
);

CREATE TABLE service_city_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id VARCHAR(80) NOT NULL,
    city_slug VARCHAR(60) NOT NULL,
    page_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    region_content_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    content_quality_passed BOOLEAN NOT NULL DEFAULT FALSE,
    author_id BIGINT NULL,
    reviewer_id BIGINT NULL,
    reviewed_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT uk_service_city UNIQUE (service_id, city_slug)
);

CREATE TABLE service_city_quality_issues (
    page_id BIGINT NOT NULL REFERENCES service_city_pages(id),
    ord INT NOT NULL,
    issue VARCHAR(500),
    PRIMARY KEY (page_id, ord)
);

CREATE TABLE service_city_regional_blocks (
    page_id BIGINT NOT NULL REFERENCES service_city_pages(id),
    ord INT NOT NULL,
    block_text VARCHAR(4000),
    PRIMARY KEY (page_id, ord)
);

CREATE TABLE service_city_faq (
    page_id BIGINT NOT NULL REFERENCES service_city_pages(id),
    ord INT NOT NULL,
    question VARCHAR(300),
    answer VARCHAR(2000),
    PRIMARY KEY (page_id, ord)
);

CREATE TABLE service_city_cases (
    page_id BIGINT NOT NULL REFERENCES service_city_pages(id),
    ord INT NOT NULL,
    case_text VARCHAR(2000),
    PRIMARY KEY (page_id, ord)
);

-- Seed cities with editorially-verified case forms (not algorithmically derived - see City.java
-- javadoc). Семей is the exact example called out by the acceptance criteria: nominative "Семей",
-- prepositional (в) "Семее", genitive (из) "Семея" - never the naive "в Семей"/"из Семей".
INSERT INTO content_cities (slug, nominative, genitive, dative, accusative, instrumental, prepositional, region_name) VALUES
    ('almaty', 'Алматы', 'Алматы', 'Алматы', 'Алматы', 'Алматы', 'Алматы', 'Алматинская область'),
    ('astana', 'Астана', 'Астаны', 'Астане', 'Астану', 'Астаной', 'Астане', 'город республиканского значения'),
    ('semey', 'Семей', 'Семея', 'Семею', 'Семей', 'Семеем', 'Семее', 'Абайская область'),
    ('shymkent', 'Шымкент', 'Шымкента', 'Шымкенту', 'Шымкент', 'Шымкентом', 'Шымкенте', 'город республиканского значения'),
    ('karaganda', 'Караганда', 'Караганды', 'Караганде', 'Караганду', 'Карагандой', 'Караганде', 'Карагандинская область'),
    ('aktobe', 'Актобе', 'Актобе', 'Актобе', 'Актобе', 'Актобе', 'Актобе', 'Актюбинская область');
