import { useState } from 'react';
import Button from '../../../../components/ui/Button';
import Modal from '../../../../components/ui/Modal';
import { signBase64WithNCALayer } from '../../../../services/ncalayer';
import { asPekRecord } from '../../api/pekMappers';
import { pekService } from '../../api/pekService';

const PekSignModal=({open,reportId,version,pending,onClose,onSigned}:{open:boolean;reportId:number;version:number;pending:boolean;onClose:()=>void;onSigned:(body:Record<string,unknown>|FormData)=>void})=>{const [mode,setMode]=useState<'CMS'|'UPLOAD'>('CMS');const [file,setFile]=useState<File|null>(null);const [signer,setSigner]=useState('');const [date,setDate]=useState('');const [comment,setComment]=useState('');const [preparing,setPreparing]=useState(false);const [error,setError]=useState('');const submit=async()=>{setError('');if(mode==='UPLOAD'){if(!file||!signer||!date)return;const data=new FormData();data.append('file',file);data.append('signer',signer);data.append('signedAt',date);data.append('comment',comment);data.append('version',String(version));data.append('mode','UPLOAD');onSigned(data);return;}setPreparing(true);try{const prepared=asPekRecord(await pekService.prepareSigning(reportId,{version}));const content=String(prepared.contentBase64||prepared.dataToSign||prepared.base64||'');if(!content)throw new Error('Backend не вернул данные для подписи.');const signed=await signBase64WithNCALayer(content);onSigned({version,mode:'CMS',cms:signed.signedCms,signerSubject:signed.signerSubject});}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить подписание');}finally{setPreparing(false);}};return <Modal open={open} title="Подписать отчёт ПЭК" loading={pending||preparing} onClose={onClose} footer={<><Button variant="secondary" disabled={pending||preparing} onClick={onClose}>Отмена</Button><Button disabled={pending||preparing||(mode==='UPLOAD'&&(!file||!signer||!date))} onClick={()=>void submit()}>Подписать</Button></>}><div className="space-y-4"><div className="flex gap-2"><Button variant={mode==='CMS'?'primary':'secondary'} onClick={()=>setMode('CMS')}>ЭЦП / CMS</Button><Button variant={mode==='UPLOAD'?'primary':'secondary'} onClick={()=>setMode('UPLOAD')}>Подписанный PDF</Button></div>{mode==='CMS'?<p className="rounded-xl bg-eco-50 p-4 text-sm">Запустите NCALayer и подключите ключ ЭЦП. Backend подготовит неизменяемые данные отчёта для подписи.</p>:<div className="grid gap-3"><label>Подписанный PDF *<input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-1 w-full rounded-xl border p-3"/></label><label>Подписант *<input value={signer} onChange={e=>setSigner(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label>Дата подписи *<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label>Комментарий<textarea value={comment} onChange={e=>setComment(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label></div>}{error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}</div></Modal>};
export default PekSignModal;
