import { Edit3, Eye, Trash2 } from 'lucide-react';
import Button from '../../../components/ui/Button';
import { LAB_JOURNAL_TYPES, type LabJournalEntry } from '../../../types/labJournal';
import { formatJournalKeyInfo } from '../api/labJournalMappers';
import { formatJournalDate, formatJournalDateTime } from '../utils/journalFormatters';
import { JournalEmptyState } from './JournalEmptyState';
import { JournalStatusChip } from './JournalStatusChip';

type Props = { entries: LabJournalEntry[]; page: number; size: number; loading: boolean; filtered: boolean; canCreate: boolean; canEdit: (entry: LabJournalEntry) => boolean; canDelete: (entry: LabJournalEntry) => boolean; onCreate: () => void; onView: (entry: LabJournalEntry) => void; onEdit: (entry: LabJournalEntry) => void; onDelete: (entry: LabJournalEntry) => void };

export const JournalEntriesTable = ({ entries, page, size, loading, filtered, canCreate, canEdit, canDelete, onCreate, onView, onEdit, onDelete }: Props) => <section className="overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead className="bg-slate-50 text-slate-700"><tr><th className="p-3">№</th><th className="p-3">Вид журнала</th><th className="p-3">Дата</th><th className="p-3">Лаборатория</th><th className="p-3">Ключевая информация</th><th className="p-3">Исполнитель</th><th className="p-3">Дата создания</th><th className="p-3">Статус</th><th className="p-3">Действия</th></tr></thead><tbody>{loading ? Array.from({ length: 5 }).map((_, row) => <tr key={row} className="border-t">{Array.from({ length: 9 }).map((__, cell) => <td key={cell} className="p-3"><div className="h-4 animate-pulse rounded bg-slate-100" /></td>)}</tr>) : entries.map((entry, index) => <tr key={entry.id} className="border-t align-top"><td className="p-3 font-bold">{page * size + index + 1}</td><td className="max-w-[220px] p-3">{LAB_JOURNAL_TYPES[entry.journalType]?.label || entry.journalType}</td><td className="p-3">{formatJournalDate(entry.entryDate)}</td><td className="p-3">{entry.laboratoryName || `№ ${entry.laboratoryId}`}</td><td className="max-w-[280px] p-3"><span className="line-clamp-3" title={formatJournalKeyInfo(entry)}>{formatJournalKeyInfo(entry)}</span></td><td className="p-3">{entry.executorName || '—'}</td><td className="p-3">{formatJournalDateTime(entry.createdAt)}</td><td className="p-3"><JournalStatusChip /></td><td className="p-3"><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" aria-label={`Просмотреть запись ${entry.id}`} title="Просмотреть" onClick={() => onView(entry)}><Eye className="h-4 w-4" /></Button>{canEdit(entry) && <Button type="button" variant="secondary" aria-label={`Редактировать запись ${entry.id}`} title="Редактировать" onClick={() => onEdit(entry)}><Edit3 className="h-4 w-4" /></Button>}{canDelete(entry) && <Button type="button" variant="secondary" aria-label={`Удалить запись ${entry.id}`} title="Удалить" onClick={() => onDelete(entry)}><Trash2 className="h-4 w-4" /></Button>}</div></td></tr>)}</tbody></table></div>{!loading && !entries.length && <JournalEmptyState filtered={filtered} canCreate={canCreate} onCreate={onCreate} />}</section>;
