package kz.eco.mail;

public enum EmailEvent {
    ORDER_CREATED,
    CONTRACT_SENT,
    CONTRACT_SIGNED,
    DOCUMENT_SENT,
    DOCUMENT_SIGNATURE_REQUIRED,
    DOCUMENT_SIGNED,
    PRIMARY_DOCS_REQUESTED,
    PRIMARY_DOCS_REVIEW,
    CLIENT_COMMENT,
    STAFF_COMMENT_TO_CLIENT,
    PAYMENT_INVOICE,
    PAYMENT_CONFIRMED
}
