import type { PekProgramForm } from '../api/pekContracts';

export const pekProgramDefaults: PekProgramForm = {
  companyId: 0,
  objectId: 0,
  number: '',
  name: '',
  description: '',
  validFrom: '',
  validUntil: '',
  responsibleUserId: null,
  regulationVersion: null,
  templateVersion: null,
  facilityInformation: '',
  kato: '',
  bin: '',
  oked: '',
  environmentalCategory: '',
  designCapacity: '',
  productionCharacteristics: '',
  monitoringScope: '',
  internalInspectionProcedure: '',
  measurementQualityAssurance: '',
  emergencyProcedures: '',
  responsibilityMatrix: '',
  permitIds: [],
  readinessNotes: '',
  controlItems: [],
  indicators: [],
  measures: [],
};
